List activitiesList = [
  ['Man in Suit Levitating', '🕴'],
  ['Man Climbing', '🧗\u200d♂️'],
  ['Woman Climbing', '🧗\u200d♀️'],
  ['Horse Racing', '🏇'],
  ['Skier', '⛷'],
  ['Snowboarder', '🏂'],
  ['Man Golfing', '🏌️\u200d♂️'],
  ['Woman Golfing', '🏌️\u200d♀️'],
  ['Man Surfing', '🏄\u200d♂️'],
  ['Woman Surfing', '🏄\u200d♀️'],
  ['Man Rowing Boat', '🚣\u200d♂️'],
  ['Woman Rowing Boat', '🚣\u200d♀️'],
  ['Man Swimming', '🏊\u200d♂️'],
  ['Woman Swimming', '🏊\u200d♀️'],
  ['Man Bouncing Ball', '⛹️\u200d♂️'],
  ['Woman Bouncing Ball', '⛹️\u200d♀️'],
  ['Man Lifting Weights', '🏋️\u200d♂️'],
  ['Woman Lifting Weights', '🏋️\u200d♀️'],
  ['Man Biking', '🚴\u200d♂️'],
  ['Woman Biking', '🚴\u200d♀️'],
  ['Man Mountain Biking', '🚵\u200d♂️'],
  ['Woman Mountain Biking', '🚵\u200d♀️'],
  ['Man Cartwheeling', '🤸\u200d♂️'],
  ['Woman Cartwheeling', '🤸\u200d♀️'],
  ['Men Wrestling', '🤼\u200d♂️'],
  ['Women Wrestling', '🤼\u200d♀️'],
  ['Man Playing Water Polo', '🤽\u200d♂️'],
  ['Woman Playing Water Polo', '🤽\u200d♀️'],
  ['Man Playing Handball', '🤾\u200d♂️'],
  ['Woman Playing Handball', '🤾\u200d♀️'],
  ['Man Juggling', '🤹\u200d♂️'],
  ['Woman Juggling', '🤹\u200d♀️'],
  ['Man in Lotus Position', '🧘\u200d♂️'],
  ['Woman in Lotus Position', '🧘\u200d♀️'],
  ['Circus Tent', '🎪'],
  ['Skateboard', '🛹'],
  ['Reminder Ribbon', '🎗'],
  ['Admission Tickets', '🎟'],
  ['Ticket', '🎫'],
  ['Military Medal', '🎖'],
  ['Trophy', '🏆'],
  ['Sports Medal', '🏅'],
  ['1st Place Medal', '🥇'],
  ['2nd Place Medal', '🥈'],
  ['3rd Place Medal', '🥉'],
  ['Soccer Ball', '⚽'],
  ['Baseball', '⚾'],
  ['Softball', '🥎'],
  ['Basketball', '🏀'],
  ['Volleyball', '🏐'],
  ['American Football', '🏈'],
  ['Rugby Football', '🏉'],
  ['Tennis', '🎾'],
  ['Flying Disc', '🥏'],
  ['Bowling', '🎳'],
  ['Cricket Game', '🏏'],
  ['Field Hockey', '🏑'],
  ['Ice Hockey', '🏒'],
  ['Lacrosse', '🥍'],
  ['Ping Pong', '🏓'],
  ['Badminton', '🏸'],
  ['Boxing Glove', '🥊'],
  ['Martial Arts Uniform', '🥋'],
  ['Flag in Hole', '⛳'],
  ['Ice Skate', '⛸'],
  ['Fishing Pole', '🎣'],
  ['Running Shirt', '🎽'],
  ['Skis', '🎿'],
  ['Sled', '🛷'],
  ['Curling Stone', '🥌'],
  ['Direct Hit', '🎯'],
  ['Pool 8 Ball', '🎱'],
  ['Video Game', '🎮'],
  ['Slot Machine', '🎰'],
  ['Game Die', '🎲'],
  ['Jigsaw', '🧩'],
  ['Chess Pawn', '♟'],
  ['Performing Arts', '🎭'],
  ['Artist Palette', '🎨'],
  ['Thread', '🧵'],
  ['Yarn', '🧶'],
  ['Musical Score', '🎼'],
  ['Microphone', '🎤'],
  ['Headphone', '🎧'],
  ['Saxophone', '🎷'],
  ['Guitar', '🎸'],
  ['Musical Keyboard', '🎹'],
  ['Trumpet', '🎺'],
  ['Violin', '🎻'],
  ['Drum', '🥁'],
  ['Clapper Board', '🎬'],
  ['Bow and Arrow', '🏹']
];