List foodsList = [
  ['Grapes', '🍇'],
  ['Melon', '🍈'],
  ['Watermelon', '🍉'],
  ['Tangerine', '🍊'],
  ['Lemon', '🍋'],
  ['Banana', '🍌'],
  ['Pineapple', '🍍'],
  ['Mango', '🥭'],
  ['Red Apple', '🍎'],
  ['Green Apple', '🍏'],
  ['Pear', '🍐'],
  ['Peach', '🍑'],
  ['Cherries', '🍒'],
  ['Strawberry', '🍓'],
  ['Kiwi Fruit', '🥝'],
  ['Tomato', '🍅'],
  ['Coconut', '🥥'],
  ['Avocado', '🥑'],
  ['Eggplant', '🍆'],
  ['Potato', '🥔'],
  ['Carrot', '🥕'],
  ['Ear of Corn', '🌽'],
  ['Hot Pepper', '🌶'],
  ['Cucumber', '🥒'],
  ['Leafy Green', '🥬'],
  ['Broccoli', '🥦'],
  ['Mushroom', '🍄'],
  ['Peanuts', '🥜'],
  ['Chestnut', '🌰'],
  ['Bread', '🍞'],
  ['Croissant', '🥐'],
  ['Baguette Bread', '🥖'],
  ['Pretzel', '🥨'],
  ['Bagel', '🥯'],
  ['Pancakes', '🥞'],
  ['Cheese Wedge', '🧀'],
  ['Meat on Bone', '🍖'],
  ['Poultry Leg', '🍗'],
  ['Cut of Meat', '🥩'],
  ['Bacon', '🥓'],
  ['Hamburger', '🍔'],
  ['French Fries', '🍟'],
  ['Pizza', '🍕'],
  ['Hot Dog', '🌭'],
  ['Sandwich', '🥪'],
  ['Taco', '🌮'],
  ['Burrito', '🌯'],
  ['Stuffed Flatbread', '🥙'],
  ['Cooking', '🍳'],
  ['Shallow Pan of Food', '🥘'],
  ['Pot of Food', '🍲'],
  ['Bowl With Spoon', '🥣'],
  ['Green Salad', '🥗'],
  ['Popcorn', '🍿'],
  ['Salt', '🧂'],
  ['Canned Food', '🥫'],
  ['Bento Box', '🍱'],
  ['Rice Cracker', '🍘'],
  ['Rice Ball', '🍙'],
  ['Cooked Rice', '🍚'],
  ['Curry Rice', '🍛'],
  ['Steaming Bowl', '🍜'],
  ['Spaghetti', '🍝'],
  ['Roasted Sweet Potato', '🍠'],
  ['Oden', '🍢'],
  ['Sushi', '🍣'],
  ['Fried Shrimp', '🍤'],
  ['Fish Cake With Swirl', '🍥'],
  ['Moon Cake', '🥮'],
  ['Dango', '🍡'],
  ['Dumpling', '🥟'],
  ['Fortune Cookie', '🥠'],
  ['Takeout Box', '🥡'],
  ['Soft Ice Cream', '🍦'],
  ['Shaved Ice', '🍧'],
  ['Ice Cream', '🍨'],
  ['Doughnut', '🍩'],
  ['Cookie', '🍪'],
  ['Birthday Cake', '🎂'],
  ['Shortcake', '🍰'],
  ['Cupcake', '🧁'],
  ['Pie', '🥧'],
  ['Chocolate Bar', '🍫'],
  ['Candy', '🍬'],
  ['Lollipop', '🍭'],
  ['Custard', '🍮'],
  ['Honey Pot', '🍯'],
  ['Baby Bottle', '🍼'],
  ['Glass of Milk', '🥛'],
  ['Hot Beverage', '☕'],
  ['Teacup Without Handle', '🍵'],
  ['Sake', '🍶'],
  ['Bottle With Popping Cork', '🍾'],
  ['Wine Glass', '🍷'],
  ['Cocktail Glass', '🍸'],
  ['Tropical Drink', '🍹'],
  ['Beer Mug', '🍺'],
  ['Clinking Beer Mugs', '🍻'],
  ['Clinking Glasses', '🥂'],
  ['Tumbler Glass', '🥃'],
  ['Cup With Straw', '🥤'],
  ['Chopsticks', '🥢'],
  ['Fork and Knife With Plate', '🍽'],
  ['Fork and Knife', '🍴'],
  ['Spoon', '🥄'],
];