List objectsList = [
  ['Love Letter', '💌'],
  ['Hole', '🕳️'],
  ['Bomb', '💣'],
  ['Person Taking Bath', '🛀'],
  ['Person in Bed', '🛌'],
  ['Kitchen Knife', '🔪'],
  ['Amphora', '🏺'],
  ['World Map', '🗺️'],
  ['Compass', '🧭'],
  ['Brick', '🧱'],
  ['Barber Pole', '💈'],
  ['Manual Wheelchair', '🦽'],
  ['Motorized Wheelchair', '🦼'],
  ['Oil Drum', '🛢️'],
  ['Bellhop Bell', '🛎️'],
  ['Luggage', '🧳'],
  ['Hourglass Done', '⌛'],
  ['Hourglass Not Done', '⏳'],
  ['Watch', '⌚'],
  ['Alarm Clock', '⏰'],
  ['Stopwatch', '⏱️'],
  ['Timer Clock', '⏲️'],
  ['Mantelpiece Clock', '🕰️'],
  ['Thermometer', '🌡️'],
  ['Umbrella on Ground', '⛱️'],
  ['Firecracker', '🧨'],
  ['Balloon', '🎈'],
  ['Party Popper', '🎉'],
  ['Confetti Ball', '🎊'],
  ['Japanese Dolls', '🎎'],
  ['Carp Streamer', '🎏'],
  ['Wind Chime', '🎐'],
  ['Red Envelope', '🧧'],
  ['Ribbon', '🎀'],
  ['Wrapped Gift', '🎁'],
  ['Diving Mask', '🤿'],
  ['Yo-Yo', '🪀'],
  ['Kite', '🪁'],
  ['Crystal Ball', '🔮'],
  ['Magic Wand', '🪄'],
  ['Nazar Amulet', '🧿'],
  ['Joystick', '🕹️'],
  ['Teddy Bear', '🧸'],
  ['Piñata', '🪅'],
  ['Nesting Dolls', '🪆'],
  ['Framed Picture', '🖼️'],
  ['Thread', '🧵'],
  ['Sewing Needle', '🪡'],
  ['Yarn', '🧶'],
  ['Knot', '🪢'],
  ['Shopping Bags', '🛍️'],
  ['Prayer Beads', '📿'],
  ['Gem Stone', '💎'],
  ['Postal Horn', '📯'],
  ['Studio Microphone', '🎙️'],
  ['Level Slider', '🎚️'],
  ['Control Knobs', '🎛️'],
  ['Radio', '📻'],
  ['Banjo', '🪕'],
  ['Mobile Phone', '📱'],
  ['Mobile Phone with Arrow', '📲'],
  ['Telephone', '☎️'],
  ['Telephone Receiver', '📞'],
  ['Pager', '📟'],
  ['Fax Machine', '📠'],
  ['Battery', '🔋'],
  ['Electric Plug', '🔌'],
  ['Laptop', '💻'],
  ['Desktop Computer', '🖥️'],
  ['Printer', '🖨️'],
  ['Keyboard', '⌨️'],
  ['Computer Mouse', '🖱️'],
  ['Trackball', '🖲️'],
  ['Computer Disk', '💽'],
  ['Floppy Disk', '💾'],
  ['Optical Disk', '💿'],
  ['DVD', '📀'],
  ['Abacus', '🧮'],
  ['Movie Camera', '🎥'],
  ['Film Frames', '🎞️'],
  ['Film Projector', '📽️'],
  ['Television', '📺'],
  ['Camera', '📷'],
  ['Camera with Flash', '📸'],
  ['Video Camera', '📹'],
  ['Videocassette', '📼'],
  ['Magnifying Glass Tilted Left', '🔍'],
  ['Magnifying Glass Tilted Right', '🔎'],
  ['Candle', '🕯️'],
  ['Light Bulb', '💡'],
  ['Flashlight', '🔦'],
  ['Red Paper Lantern', '🏮'],
  ['Diya Lamp', '🪔'],
  ['Notebook with Decorative Cover', '📔'],
  ['Closed Book', '📕'],
  ['Open Book', '📖'],
  ['Green Book', '📗'],
  ['Blue Book', '📘'],
  ['Orange Book', '📙'],
  ['Books', '📚'],
  ['Notebook', '📓'],
  ['Ledger', '📒'],
  ['Page with Curl', '📃'],
  ['Scroll', '📜'],
  ['Page Facing Up', '📄'],
  ['Newspaper', '📰'],
  ['Rolled-Up Newspaper', '🗞️'],
  ['Bookmark Tabs', '📑'],
  ['Bookmark', '🔖'],
  ['Label', '🏷️'],
  ['Money Bag', '💰'],
  ['Coin', '🪙'],
  ['Yen Banknote', '💴'],
  ['Dollar Banknote', '💵'],
  ['Euro Banknote', '💶'],
  ['Pound Banknote', '💷'],
  ['Money with Wings', '💸'],
  ['Credit Card', '💳'],
  ['Receipt', '🧾'],
  ['Envelope', '✉️'],
  ['E-Mail', '📧'],
  ['Incoming Envelope', '📨'],
  ['Envelope with Arrow', '📩'],
  ['Outbox Tray', '📤'],
  ['Inbox Tray', '📥'],
  ['Package', '📦'],
  ['Closed Mailbox with Raised Flag', '📫'],
  ['Closed Mailbox with Lowered Flag', '📪'],
  ['Open Mailbox with Raised Flag', '📬'],
  ['Open Mailbox with Lowered Flag', '📭'],
  ['Postbox', '📮'],
  ['Ballot Box with Ballot', '🗳️'],
  ['Pencil', '✏️'],
  ['Black Nib', '✒️'],
  ['Fountain Pen', '🖋️'],
  ['Pen', '🖊️'],
  ['Paintbrush', '🖌️'],
  ['Crayon', '🖍️'],
  ['Memo', '📝'],
  ['File Folder', '📁'],
  ['Open File Folder', '📂'],
  ['Card Index Dividers', '🗂️'],
  ['Calendar', '📅'],
  ['Tear-Off Calendar', '📆'],
  ['Spiral Notepad', '🗒️'],
  ['Spiral Calendar', '🗓️'],
  ['Card Index', '📇'],
  ['Chart Increasing', '📈'],
  ['Chart Decreasing', '📉'],
  ['Bar Chart', '📊'],
  ['Clipboard', '📋'],
  ['Pushpin', '📌'],
  ['Round Pushpin', '📍'],
  ['Paperclip', '📎'],
  ['Linked Paperclips', '🖇️'],
  ['Straight Ruler', '📏'],
  ['Triangular Ruler', '📐'],
  ['Scissors', '✂️'],
  ['Card File Box', '🗃️'],
  ['File Cabinet', '🗄️'],
  ['Wastebasket', '🗑️'],
  ['Locked', '🔒'],
  ['Unlocked', '🔓'],
  ['Locked with Pen', '🔏'],
  ['Locked with Key', '🔐'],
  ['Key', '🔑'],
  ['Old Key', '🗝️'],
  ['Hammer', '🔨'],
  ['Axe', '🪓'],
  ['Pick', '⛏️'],
  ['Hammer and Pick', '⚒️'],
  ['Hammer and Wrench', '🛠️'],
  ['Dagger', '🗡️'],
  ['Crossed Swords', '⚔️'],
  ['Pistol', '🔫'],
  ['Boomerang', '🪃'],
  ['Shield', '🛡️'],
  ['Carpentry Saw', '🪚'],
  ['Wrench', '🔧'],
  ['Screwdriver', '🪛'],
  ['Nut and Bolt', '🔩'],
  ['Gear', '⚙️'],
  ['Clamp', '🗜️'],
  ['Balance Scale', '⚖️'],
  ['White Cane', '🦯'],
  ['Link', '🔗'],
  ['Chains', '⛓️'],
  ['Hook', '🪝'],
  ['Toolbox', '🧰'],
  ['Magnet', '🧲'],
  ['Ladder', '🪜'],
  ['Alembic', '⚗️'],
  ['Test Tube', '🧪'],
  ['Petri Dish', '🧫'],
  ['DNA', '🧬'],
  ['Microscope', '🔬'],
  ['Telescope', '🔭'],
  ['Satellite Antenna', '📡'],
  ['Syringe', '💉'],
  ['Drop of Blood', '🩸'],
  ['Pill', '💊'],
  ['Adhesive Bandage', '🩹'],
  ['Stethoscope', '🩺'],
  ['Door', '🚪'],
  ['Mirror', '🪞'],
  ['Window', '🪟'],
  ['Bed', '🛏️'],
  ['Couch and Lamp', '🛋️'],
  ['Chair', '🪑'],
  ['Toilet', '🚽'],
  ['Plunger', '🪠'],
  ['Shower', '🚿'],
  ['Bathtub', '🛁'],
  ['Mouse Trap', '🪤'],
  ['Razor', '🪒'],
  ['Lotion Bottle', '🧴'],
  ['Safety Pin', '🧷'],
  ['Broom', '🧹'],
  ['Basket', '🧺'],
  ['Roll of Paper', '🧻'],
  ['Bucket', '🪣'],
  ['Soap', '🧼'],
  ['Toothbrush', '🪥'],
  ['Sponge', '🧽'],
  ['Fire Extinguisher', '🧯'],
  ['Shopping Cart', '🛒'],
  ['Cigarette', '🚬'],
  ['Coffin', '⚰️'],
  ['Headstone', '🪦'],
  ['Funeral Urn', '⚱️'],
  ['Moai', '🗿'],
  ['Placard', '🪧'],
  ['Potable Water', '🚰']
];