List smileysList = [
  ['Grinning Face', '😀'],
  ['Grinning Face With Big Eyes', '😃'],
  ['Grinning Face With Smiling Eyes', '😄'],
  ['Beaming Face With Smiling Eyes', '😁'],
  ['Grinning Squinting Face', '😆'],
  ['Grinning Face With Sweat', '😅'],
  ['Rolling on the Floor Laughing', '🤣'],
  ['Face With Tears of Joy', '😂'],
  ['Slightly Smiling Face', '🙂'],
  ['Upside-Down Face', '🙃'],
  ['Winking Face', '😉'],
  ['Smiling Face With Smiling Eyes', '😊'],
  ['Smiling Face With Halo', '😇'],
  ['Smiling Face With Hearts', '🥰'],
  ['Smiling Face With Heart-Eyes', '😍'],
  ['Star-Struck', '🤩'],
  ['Face Blowing a Kiss', '😘'],
  ['Kissing Face', '😗'],
  ['Smiling Face', '☺'],
  ['Kissing Face With Closed Eyes', '😚'],
  ['Kissing Face With Smiling Eyes', '😙'],
  ['Face Savoring Food', '😋'],
  ['Face With Tongue', '😛'],
  ['Winking Face With Tongue', '😜'],
  ['Zany Face', '🤪'],
  ['Squinting Face With Tongue', '😝'],
  ['Money-Mouth Face', '🤑'],
  ['Hugging Face', '🤗'],
  ['Face With Hand Over Mouth', '🤭'],
  ['Shushing Face', '🤫'],
  ['Thinking Face', '🤔'],
  ['Zipper-Mouth Face', '🤐'],
  ['Face With Raised Eyebrow', '🤨'],
  ['Neutral Face', '😐'],
  ['Expressionless Face', '😑'],
  ['Face Without Mouth', '😶'],
  ['Smirking Face', '😏'],
  ['Unamused Face', '😒'],
  ['Face With Rolling Eyes', '🙄'],
  ['Grimacing Face', '😬'],
  ['Lying Face', '🤥'],
  ['Relieved Face', '😌'],
  ['Pensive Face', '😔'],
  ['Sleepy Face', '😪'],
  ['Drooling Face', '🤤'],
  ['Sleeping Face', '😴'],
  ['Face With Medical Mask', '😷'],
  ['Face With Thermometer', '🤒'],
  ['Face With Head-Bandage', '🤕'],
  ['Nauseated Face', '🤢'],
  ['Face Vomiting', '🤮'],
  ['Sneezing Face', '🤧'],
  ['Hot Face', '🥵'],
  ['Cold Face', '🥶'],
  ['Woozy Face', '🥴'],
  ['Dizzy Face', '😵'],
  ['Exploding Head', '🤯'],
  ['Cowboy Hat Face', '🤠'],
  ['Partying Face', '🥳'],
  ['Smiling Face With Sunglasses', '😎'],
  ['Nerd Face', '🤓'],
  ['Face With Monocle', '🧐'],
  ['Confused Face', '😕'],
  ['Worried Face', '😟'],
  ['Slightly Frowning Face', '🙁'],
  ['Frowning Face', '☹\ufe0f'],
  ['Face With Open Mouth', '\ud83d\udea3'],
  ['Hushed Face', '😯'],
  ['Astonished Face', '😲'],
  ['Flushed Face', '😳'],
  ['Pleading Face', '🥺'],
  ['Frowning Face With Open Mouth', '😦'],
  ['Anguished Face', '😧'],
  ['Fearful Face', '😨'],
  ['Anxious Face With Sweat', '😰'],
  ['Sad but Relieved Face', '😥'],
  ['Crying Face', '😢'],
  ['Loudly Crying Face', '😭'],
  ['Face Screaming in Fear', '😱'],
  ['Confounded Face', '😖'],
  ['Persevering Face', '😣'],
  ['Disappointed Face', '😞'],
  ['Downcast Face With Sweat', '😓'],
  ['Weary Face', '😩'],
  ['Tired Face', '😫'],
  ['Face With Steam From Nose', '😤'],
  ['Pouting Face', '😡'],
  ['Angry Face', '😠'],
  ['Face With Symbols on Mouth', '🤬'],
  ['Smiling Face With Horns', '😈'],
  ['Angry Face With Horns', '👿'],
  ['Skull', '💀'],
  ['Skull and Crossbones', '☠'],
  ['Pile of Poo', '💩'],
  ['Clown Face', '🤡'],
  ['Ogre', '👹'],
  ['Goblin', '👺'],
  ['Ghost', '👻'],
  ['Alien', '👽'],
  ['Alien Monster', '👾'],
  ['Robot Face', '🤖'],
  ['Grinning Cat Face', '😺'],
  ['Grinning Cat Face With Smiling Eyes', '😸'],
  ['Cat Face With Tears of Joy', '😹'],
  ['Smiling Cat Face With Heart-Eyes', '😻'],
  ['Cat Face With Wry Smile', '😼'],
  ['Kissing Cat Face', '😽'],
  ['Weary Cat Face', '🙀'],
  ['Crying Cat Face', '😿'],
  ['Pouting Cat Face', '😾'],
  ['Kiss Mark', '💋'],
  ['Waving Hand', '👋'],
  ['Raised Back of Hand', '🤚'],
  ['Hand With Fingers Splayed', '🖐'],
  ['Raised Hand', '✋'],
  ['Vulcan Salute', '🖖'],
  ['OK Hand', '👌'],
  ['Victory Hand', '✌'],
  ['Crossed Fingers', '🤞'],
  ['Love-You Gesture', '🤟'],
  ['Sign of the Horns', '🤘'],
  ['Call Me Hand', '🤙'],
  ['Backhand Index Pointing Left', '👈'],
  ['Backhand Index Pointing Right', '👉'],
  ['Backhand Index Pointing Up', '👆'],
  ['Middle Finger', '🖕'],
  ['Backhand Index Pointing Down', '👇'],
  ['Index Pointing Up', '☝'],
  ['Thumbs Up', '👍'],
  ['Thumbs Down', '👎'],
  ['Raised Fist', '✊'],
  ['Oncoming Fist', '👊'],
  ['Left-Facing Fist', '🤛'],
  ['Right-Facing Fist', '🤜'],
  ['Clapping Hands', '👏'],
  ['Raising Hands', '🙌'],
  ['Open Hands', '👐'],
  ['Palms Up Together', '🤲'],
  ['Handshake', '🤝'],
  ['Folded Hands', '🙏'],
  ['Writing Hand', '✍'],
  ['Nail Polish', '💅'],
  ['Selfie', '🤳'],
  ['Flexed Biceps', '💪'],
  ['Leg', '🦵'],
  ['Foot', '🦶'],
  ['Ear', '👂'],
  ['Nose', '👃'],
  ['Brain', '🧠'],
  ['Tooth', '🦷'],
  ['Bone', '🦴'],
  ['Eyes', '👀'],
  ['Eye', '👁'],
  ['Tongue', '👅'],
  ['Mouth', '👄'],
  ['Baby', '👶'],
  ['Child', '🧒'],
  ['Boy', '👦'],
  ['Girl', '👧'],
  ['Person', '🧑'],
  ['Man', '👨'],
  ['Man: Beard', '🧔'],
  ['Man: Blond Hair', '👱\u200d♂️'],
  ['Man: Red Hair', '👨\u200d🦰'],
  ['Man: Curly Hair', '👨\u200d🦱'],
  ['Man: White Hair', '👨\u200d🦳'],
  ['Man: Bald', '👨\u200d🦲'],
  ['Woman', '👩'],
  ['Woman: Blond Hair', '👱\u200d♀️'],
  ['Woman: Red Hair', '👩\u200d🦰'],
  ['Woman: Curly Hair', '👩\u200d🦱'],
  ['Woman: White Hair', '👩\u200d🦳'],
  ['Woman: Bald', '👩\u200d🦲'],
  ['Older Person', '🧓'],
  ['Old Man', '👴'],
  ['Old Woman', '👵'],
  ['Man Frowning', '🙍\u200d♂️'],
  ['Woman Frowning', '🙍\u200d♀️'],
  ['Man Pouting', '🙎\u200d♂️'],
  ['Woman Pouting', '🙎\u200d♀️'],
  ['Man Gesturing No', '🙅\u200d♂️'],
  ['Woman Gesturing No', '🙅\u200d♀️'],
  ['Man Gesturing OK', '🙆\u200d♂️'],
  ['Woman Gesturing OK', '🙆\u200d♀️'],
  ['Man Tipping Hand', '💁\u200d♂️'],
  ['Woman Tipping Hand', '💁\u200d♀️'],
  ['Man Raising Hand', '🙋\u200d♂️'],
  ['Woman Raising Hand', '🙋\u200d♀️'],
  ['Man Bowing', '🙇\u200d♂️'],
  ['Woman Bowing', '🙇\u200d♀️'],
  ['Man Facepalming', '🤦\u200d♂️'],
  ['Woman Facepalming', '🤦\u200d♀️'],
  ['Man Shrugging', '🤷\u200d♂️'],
  ['Woman Shrugging', '🤷\u200d♀️'],
  ['Man Health Worker', '👨\u200d⚕️'],
  ['Woman Health Worker', '👩\u200d⚕️'],
  ['Man Student', '👨\u200d🎓'],
  ['Woman Student', '👩\u200d🎓'],
  ['Man Teacher', '👨\u200d🏫'],
  ['Woman Teacher', '👩\u200d🏫'],
  ['Man Judge', '👨\u200d⚖️'],
  ['Woman Judge', '👩\u200d⚖️'],
  ['Man Farmer', '👨\u200d🌾'],
  ['Woman Farmer', '👩\u200d🌾'],
  ['Man Cook', '👨\u200d🍳'],
  ['Woman Cook', '👩\u200d🍳'],
  ['Man Mechanic', '👨\u200d🔧'],
  ['Woman Mechanic', '👩\u200d🔧'],
  ['Man Factory Worker', '👨\u200d🏭'],
  ['Woman Factory Worker', '👩\u200d🏭'],
  ['Man Office Worker', '👨\u200d💼'],
  ['Woman Office Worker', '👩\u200d💼'],
  ['Man Scientist', '👨\u200d🔬'],
  ['Woman Scientist', '👩\u200d🔬'],
  ['Man Technologist', '👨\u200d💻'],
  ['Woman Technologist', '👩\u200d💻'],
  ['Man Singer', '👨\u200d🎤'],
  ['Woman Singer', '👩\u200d🎤'],
  ['Man Artist', '👨\u200d🎨'],
  ['Woman Artist', '👩\u200d🎨'],
  ['Man Pilot', '👨\u200d✈️'],
  ['Woman Pilot', '👩\u200d✈️'],
  ['Man Astronaut', '👨\u200d🚀'],
  ['Woman Astronaut', '👩\u200d🚀'],
  ['Man Firefighter', '👨\u200d🚒'],
  ['Woman Firefighter', '👩\u200d🚒'],
  ['Man Police Officer', '👮\u200d♂️'],
  ['Woman Police Officer', '👮\u200d♀️'],
  ['Man Detective', '🕵️\u200d♂️'],
  ['Woman Detective', '🕵️\u200d♀️'],
  ['Man Guard', '💂\u200d♂️'],
  ['Woman Guard', '💂\u200d♀️'],
  ['Man Construction Worker', '👷\u200d♂️'],
  ['Woman Construction Worker', '👷\u200d♀️'],
  ['Prince', '🤴'],
  ['Princess', '👸'],
  ['Man Wearing Turban', '👳\u200d♂️'],
  ['Woman Wearing Turban', '👳\u200d♀️'],
  ['Man With Chinese Cap', '👲'],
  ['Woman With Headscarf', '🧕'],
  ['Man in Tuxedo', '🤵'],
  ['Bride With Veil', '👰'],
  ['Pregnant Woman', '🤰'],
  ['Breast-Feeding', '🤱'],
  ['Baby Angel', '👼'],
  ['Santa Claus', '🎅'],
  ['Mrs. Claus', '🤶'],
  ['Man Superhero', '🦸\u200d♂️'],
  ['Woman Superhero', '🦸\u200d♀️'],
  ['Man Supervillain', '🦹\u200d♂️'],
  ['Woman Supervillain', '🦹\u200d♀️'],
  ['Man Mage', '🧙\u200d♂️'],
  ['Woman Mage', '🧙\u200d♀️'],
  ['Man Fairy', '🧚\u200d♂️'],
  ['Woman Fairy', '🧚\u200d♀️'],
  ['Man Vampire', '🧛\u200d♂️'],
  ['Woman Vampire', '🧛\u200d♀️'],
  ['Merman', '🧜\u200d♂️'],
  ['Mermaid', '🧜\u200d♀️'],
  ['Man Elf', '🧝\u200d♂️'],
  ['Woman Elf', '🧝\u200d♀️'],
  ['Man Genie', '🧞\u200d♂️'],
  ['Woman Genie', '🧞\u200d♀️'],
  ['Man Zombie', '🧟\u200d♂️'],
  ['Woman Zombie', '🧟\u200d♀️'],
  ['Man Getting Massage', '💆\u200d♂️'],
  ['Woman Getting Massage', '💆\u200d♀️'],
  ['Man Getting Haircut', '💇\u200d♂️'],
  ['Woman Getting Haircut', '💇\u200d♀️'],
  ['Man Walking', '🚶\u200d♂️'],
  ['Woman Walking', '🚶\u200d♀️'],
  ['Man Running', '🏃\u200d♂️'],
  ['Woman Running', '🏃\u200d♀️'],
  ['Woman Dancing', '💃'],
  ['Man Dancing', '🕺'],
  ['Man in Suit Levitating', '🕴'],
  ['Men With Bunny Ears', '👯\u200d♂️'],
  ['Women With Bunny Ears', '👯\u200d♀️'],
  ['Man in Steamy Room', '🧖\u200d♂️'],
  ['Woman in Steamy Room', '🧖\u200d♀️'],
  ['Person in Lotus Position', '🧘'],
  ['Women Holding Hands', '👭'],
  ['Woman and Man Holding Hands', '👫'],
  ['Men Holding Hands', '👬'],
  ['Kiss', '💏'],
  ['Kiss: Man, Man', '👨\u200d❤️\u200d💋\u200d👨'],
  ['Kiss: Woman, Woman', '👩\u200d❤️\u200d💋\u200d👩'],
  ['Couple With Heart', '💑'],
  ['Couple With Heart: Man, Man', '👨\u200d❤️\u200d👨'],
  ['Couple With Heart: Woman, Woman', '👩\u200d❤️\u200d👩'],
  ['Family', '👪'],
  ['Family: Man, Woman, Boy', '👨\u200d👩\u200d👦'],
  ['Family: Man, Woman, Girl', '👨\u200d👩\u200d👧'],
  ['Family: Man, Woman, Girl, Boy', '👨\u200d👩\u200d👧\u200d👦'],
  ['Family: Man, Woman, Boy, Boy', '👨\u200d👩\u200d👦\u200d👦'],
  ['Family: Man, Woman, Girl, Girl', '👨\u200d👩\u200d👧\u200d👧'],
  ['Family: Man, Man, Boy', '👨\u200d👨\u200d👦'],
  ['Family: Man, Man, Girl', '👨\u200d👨\u200d👧'],
  ['Family: Man, Man, Girl, Boy', '👨\u200d👨\u200d👧\u200d👦'],
  ['Family: Man, Man, Boy, Boy', '👨\u200d👨\u200d👦\u200d👦'],
  ['Family: Man, Man, Girl, Girl', '👨\u200d👨\u200d👧\u200d👧'],
  ['Family: Woman, Woman, Boy', '👩\u200d👩\u200d👦'],
  ['Family: Woman, Woman, Girl', '👩\u200d👩\u200d👧'],
  ['Family: Woman, Woman, Girl, Boy', '👩\u200d👩\u200d👧\u200d👦'],
  ['Family: Woman, Woman, Boy, Boy', '👩\u200d👩\u200d👦\u200d👦'],
  ['Family: Woman, Woman, Girl, Girl', '👩\u200d👩\u200d👧\u200d👧'],
  ['Family: Man, Boy', '👨\u200d👦'],
  ['Family: Man, Boy, Boy', '👨\u200d👦\u200d👦'],
  ['Family: Man, Girl', '👨\u200d👧'],
  ['Family: Man, Girl, Boy', '👨\u200d👧\u200d👦'],
  ['Family: Man, Girl, Girl', '👨\u200d👧\u200d👧'],
  ['Family: Woman, Boy', '👩\u200d👦'],
  ['Family: Woman, Boy, Boy', '👩\u200d👦\u200d👦'],
  ['Family: Woman, Girl', '👩\u200d👧'],
  ['Family: Woman, Girl, Boy', '👩\u200d👧\u200d👦'],
  ['Family: Woman, Girl, Girl', '👩\u200d👧\u200d👧'],
  ['Speaking Head', '🗣'],
  ['Bust in Silhouette', '👤'],
  ['Busts in Silhouette', '👥'],
  ['Footprints', '👣'],
  ['Luggage', '🧳'],
  ['Closed Umbrella', '🌂'],
  ['Umbrella', '☂'],
  ['Thread', '🧵'],
  ['Yarn', '🧶'],
  ['Glasses', '👓'],
  ['Sunglasses', '🕶'],
  ['Goggles', '🥽'],
  ['Lab Coat', '🥼'],
  ['Necktie', '👔'],
  ['T-Shirt', '👕'],
  ['Jeans', '👖'],
  ['Scarf', '🧣'],
  ['Gloves', '🧤'],
  ['Coat', '🧥'],
  ['Socks', '🧦'],
  ['Dress', '👗'],
  ['Kimono', '👘'],
  ['Bikini', '👙'],
  ['Woman’s Clothes', '👚'],
  ['Purse', '👛'],
  ['Handbag', '👜'],
  ['Clutch Bag', '👝'],
  ['Backpack', '🎒'],
  ['Man’s Shoe', '👞'],
  ['Running Shoe', '👟'],
  ['Hiking Boot', '🥾'],
  ['Flat Shoe', '🥿'],
  ['High-Heeled Shoe', '👠'],
  ['Woman’s Sandal', '👡'],
  ['Woman’s Boot', '👢'],
  ['Crown', '👑'],
  ['Woman’s Hat', '👒'],
  ['Top Hat', '🎩'],
  ['Graduation Cap', '🎓'],
  ['Billed Cap', '🧢'],
  ['Rescue Worker’s Helmet', '⛑'],
  ['Lipstick', '💄'],
  ['Ring', '💍'],
  ['Briefcase', '💼']
];