List symbolsList = [
  ['Heart With Arrow', '💘'],
  ['Heart With Ribbon', '💝'],
  ['Sparkling Heart', '💖'],
  ['Growing Heart', '💗'],
  ['Beating Heart', '💓'],
  ['Revolving Hearts', '💞'],
  ['Two Hearts', '💕'],
  ['Heart Decoration', '💟'],
  ['Heavy Heart Exclamation', '❣'],
  ['Broken Heart', '💔'],
  ['Red Heart', '❤'],
  ['Orange Heart', '🧡'],
  ['Yellow Heart', '💛'],
  ['Green Heart', '💚'],
  ['Blue Heart', '💙'],
  ['Purple Heart', '💜'],
  ['Black Heart', '🖤'],
  ['Hundred Points', '💯'],
  ['Anger Symbol', '💢'],
  ['Speech Balloon', '💬'],
  ['Eye in Speech Bubble', '👁️\u200d🗨️'],
  ['Right Anger Bubble', '🗯'],
  ['Thought Balloon', '💭'],
  ['Zzz', '💤'],
  ['White Flower', '💮'],
  ['Hot Springs', '♨'],
  ['Barber Pole', '💈'],
  ['Stop Sign', '🛑'],
  ['Twelve O’Clock', '🕛'],
  ['Twelve-Thirty', '🕧'],
  ['One O’Clock', '🕐'],
  ['One-Thirty', '🕜'],
  ['Two O’Clock', '🕑'],
  ['Two-Thirty', '🕝'],
  ['Three O’Clock', '🕒'],
  ['Three-Thirty', '🕞'],
  ['Four O’Clock', '🕓'],
  ['Four-Thirty', '🕟'],
  ['Five O’Clock', '🕔'],
  ['Five-Thirty', '🕠'],
  ['Six O’Clock', '🕕'],
  ['Six-Thirty', '🕡'],
  ['Seven O’Clock', '🕖'],
  ['Seven-Thirty', '🕢'],
  ['Eight O’Clock', '🕗'],
  ['Eight-Thirty', '🕣'],
  ['Nine O’Clock', '🕘'],
  ['Nine-Thirty', '🕤'],
  ['Ten O’Clock', '🕙'],
  ['Ten-Thirty', '🕥'],
  ['Eleven O’Clock', '🕚'],
  ['Eleven-Thirty', '🕦'],
  ['Cyclone', '🌀'],
  ['Spade Suit', '♠'],
  ['Heart Suit', '♥'],
  ['Diamond Suit', '♦'],
  ['Club Suit', '♣'],
  ['Joker', '🃏'],
  ['Mahjong Red Dragon', '🀄'],
  ['Flower Playing Cards', '🎴'],
  ['Muted Speaker', '🔇'],
  ['Speaker Low Volume', '🔈'],
  ['Speaker Medium Volume', '🔉'],
  ['Speaker High Volume', '🔊'],
  ['Loudspeaker', '📢'],
  ['Megaphone', '📣'],
  ['Postal Horn', '📯'],
  ['Bell', '🔔'],
  ['Bell With Slash', '🔕'],
  ['Musical Note', '🎵'],
  ['Musical Notes', '🎶'],
  ['ATM Sign', '🏧'],
  ['Litter in Bin Sign', '🚮'],
  ['Potable Water', '🚰'],
  ['Wheelchair Symbol', '♿'],
  ['Men’s Room', '🚹'],
  ['Women’s Room', '🚺'],
  ['Restroom', '🚻'],
  ['Baby Symbol', '🚼'],
  ['Water Closet', '🚾'],
  ['Warning', '⚠'],
  ['Children Crossing', '🚸'],
  ['No Entry', '⛔'],
  ['Prohibited', '🚫'],
  ['No Bicycles', '🚳'],
  ['No Smoking', '🚭'],
  ['No Littering', '🚯'],
  ['Non-Potable Water', '🚱'],
  ['No Pedestrians', '🚷'],
  ['No One Under Eighteen', '🔞'],
  ['Radioactive', '☢'],
  ['Biohazard', '☣'],
  ['Up Arrow', '⬆'],
  ['Up-Right Arrow', '↗'],
  ['Right Arrow', '➡'],
  ['Down-Right Arrow', '↘'],
  ['Down Arrow', '⬇'],
  ['Down-Left Arrow', '↙'],
  ['Left Arrow', '⬅'],
  ['Up-Left Arrow', '↖'],
  ['Up-Down Arrow', '↕'],
  ['Left-Right Arrow', '↔'],
  ['Right Arrow Curving Left', '↩'],
  ['Left Arrow Curving Right', '↪'],
  ['Right Arrow Curving Up', '⤴'],
  ['Right Arrow Curving Down', '⤵'],
  ['Clockwise Vertical Arrows', '🔃'],
  ['Counterclockwise Arrows Button', '🔄'],
  ['Back Arrow', '🔙'],
  ['End Arrow', '🔚'],
  ['On! Arrow', '🔛'],
  ['Soon Arrow', '🔜'],
  ['Top Arrow', '🔝'],
  ['Place of Worship', '🛐'],
  ['Atom Symbol', '⚛'],
  ['Om', '🕉'],
  ['Star of David', '✡'],
  ['Wheel of Dharma', '☸'],
  ['Yin Yang', '☯'],
  ['Latin Cross', '✝'],
  ['Orthodox Cross', '☦'],
  ['Star and Crescent', '☪'],
  ['Peace Symbol', '☮'],
  ['Menorah', '🕎'],
  ['Dotted Six-Pointed Star', '🔯'],
  ['Aries', '♈'],
  ['Taurus', '♉'],
  ['Gemini', '♊'],
  ['Cancer', '♋'],
  ['Leo', '♌'],
  ['Virgo', '♍'],
  ['Libra', '♎'],
  ['Scorpio', '♏'],
  ['Sagittarius', '♐'],
  ['Capricorn', '♑'],
  ['Aquarius', '♒'],
  ['Pisces', '♓'],
  ['Ophiuchus', '⛎'],
  ['Shuffle Tracks Button', '🔀'],
  ['Repeat Button', '🔁'],
  ['Repeat Single Button', '🔂'],
  ['Play Button', '▶'],
  ['Fast-Forward Button', '⏩'],
  ['Reverse Button', '◀'],
  ['Fast Reverse Button', '⏪'],
  ['Upwards Button', '🔼'],
  ['Fast Up Button', '⏫'],
  ['Downwards Button', '🔽'],
  ['Fast Down Button', '⏬'],
  ['Stop Button', '⏹'],
  ['Eject Button', '⏏'],
  ['Cinema', '🎦'],
  ['Dim Button', '🔅'],
  ['Bright Button', '🔆'],
  ['Antenna Bars', '📶'],
  ['Vibration Mode', '📳'],
  ['Mobile Phone Off', '📴'],
  ['Infinity', '♾'],
  ['Recycling Symbol', '♻'],
  ['Trident Emblem', '🔱'],
  ['Name Badge', '📛'],
  ['Japanese Symbol for Beginner', '🔰'],
  ['Heavy Large Circle', '⭕'],
  ['White Heavy Check Mark', '✅'],
  ['Ballot Box With Check', '☑'],
  ['Heavy Check Mark', '✔'],
  ['Heavy Multiplication X', '✖'],
  ['Cross Mark', '❌'],
  ['Cross Mark Button', '❎'],
  ['Heavy Plus Sign', '➕'],
  ['Heavy Minus Sign', '➖'],
  ['Heavy Division Sign', '➗'],
  ['Curly Loop', '➰'],
  ['Double Curly Loop', '➿'],
  ['Part Alternation Mark', '〽'],
  ['Eight-Spoked Asterisk', '✳'],
  ['Eight-Pointed Star', '✴'],
  ['Sparkle', '❇'],
  ['Double Exclamation Mark', '‼'],
  ['Exclamation Question Mark', '⁉'],
  ['Question Mark', '❓'],
  ['White Question Mark', '❔'],
  ['White Exclamation Mark', '❕'],
  ['Exclamation Mark', '❗'],
  ['Copyright', '©'],
  ['Registered', '®'],
  ['Trade Mark', '™'],
  ['Keycap Number Sign', '#️⃣'],
  ['Keycap Digit Zero', '0️⃣'],
  ['Keycap Digit One', '1️⃣'],
  ['Keycap Digit Two', '2️⃣'],
  ['Keycap Digit Three', '3️⃣'],
  ['Keycap Digit Four', '4️⃣'],
  ['Keycap Digit Five', '5️⃣'],
  ['Keycap Digit Six', '6️⃣'],
  ['Keycap Digit Seven', '7️⃣'],
  ['Keycap Digit Eight', '8️⃣'],
  ['Keycap Digit Nine', '9️⃣'],
  ['Keycap: 10', '🔟'],
  ['Input Latin Uppercase', '🔠'],
  ['Input Latin Lowercase', '🔡'],
  ['Input Numbers', '🔢'],
  ['Input Symbols', '🔣'],
  ['Input Latin Letters', '🔤'],
  ['A Button (Blood Type)', '🅰'],
  ['AB Button (Blood Type)', '🆎'],
  ['B Button (Blood Type)', '🅱'],
  ['CL Button', '🆑'],
  ['Cool Button', '🆒'],
  ['Free Button', '🆓'],
  ['Information', 'ℹ'],
  ['ID Button', '🆔'],
  ['Circled M', 'Ⓜ'],
  ['New Button', '🆕'],
  ['NG Button', '🆖'],
  ['O Button (Blood Type)', '🅾'],
  ['OK Button', '🆗'],
  ['P Button', '🅿'],
  ['SOS Button', '🆘'],
  ['Up! Button', '🆙'],
  ['Vs Button', '🆚'],
  ['Japanese “Here” Button', '🈁'],
  ['Japanese “Service Charge” Button', '🈂'],
  ['Japanese “Monthly Amount” Button', '🈷'],
  ['Japanese “Not Free of Charge” Button', '🈶'],
  ['Japanese “Reserved” Button', '🈯'],
  ['Japanese “Bargain” Button', '🉐'],
  ['Japanese “Discount” Button', '🈹'],
  ['Japanese “Free of Charge” Button', '🈚'],
  ['Japanese “Prohibited” Button', '🈲'],
  ['Japanese “Acceptable” Button', '🉑'],
  ['Japanese “Application” Button', '🈸'],
  ['Japanese “Passing Grade” Button', '🈴'],
  ['Japanese “Vacancy” Button', '🈳'],
  ['Japanese “Congratulations” Button', '㊗'],
  ['Japanese “Secret” Button', '㊙'],
  ['Japanese “Open for Business” Button', '🈺'],
  ['Japanese “No Vacancy” Button', '🈵'],
  ['Red Circle', '🔴'],
  ['Blue Circle', '🔵'],
  ['Black Circle', '⚫'],
  ['White Circle', '⚪'],
  ['Black Large Square', '⬛'],
  ['White Large Square', '⬜'],
  ['Black Medium Square', '◼'],
  ['White Medium Square', '◻'],
  ['Black Medium-Small Square', '◾'],
  ['White Medium-Small Square', '◽'],
  ['Black Small Square', '▪'],
  ['White Small Square', '▫'],
  ['Large Orange Diamond', '🔶'],
  ['Large Blue Diamond', '🔷'],
  ['Small Orange Diamond', '🔸'],
  ['Small Blue Diamond', '🔹'],
  ['Red Triangle Pointed Up', '🔺'],
  ['Red Triangle Pointed Down', '🔻'],
  ['Diamond With a Dot', '💠'],
  ['White Square Button', '🔳'],
  ['Black Square Button', '🔲']
];