List smileysList = [
  ['😀', 'grinning face', ['face', 'grin', 'grinning face'], 0],
  ['😃', 'grinning face with big eyes', ['face', 'grinning face with big eyes', 'mouth', 'open', 'smile'], 0],
  ['😄', 'grinning face with smiling eyes', ['eye', 'face', 'grinning face with smiling eyes', 'mouth', 'open', 'smile'], 0],
  ['😁', 'beaming face with smiling eyes', ['beaming face with smiling eyes', 'eye', 'face', 'grin', 'smile'], 0],
  ['😆', 'grinning squinting face', ['face', 'grinning squinting face', 'laugh', 'mouth', 'satisfied', 'smile'], 0],
  ['😅', 'grinning face with sweat', ['cold', 'face', 'grinning face with sweat', 'open', 'smile', 'sweat'], 0],
  ['🤣', 'rolling on the floor laughing', ['face', 'floor', 'laugh', 'rofl', 'rolling', 'rolling on the floor laughing', 'rotfl'], 0],
  ['😂', 'face with tears of joy', ['face', 'face with tears of joy', 'joy', 'laugh', 'tear'], 0],
  ['🙂', 'slightly smiling face', ['face', 'slightly smiling face', 'smile'], 0],
  ['🙃', 'upside-down face', ['face', 'upside-down'], 0],
  ['🫠', '⊛ melting face', ['disappear', 'dissolve', 'liquid', 'melt'], 0],
  ['😉', 'winking face', ['face', 'wink', 'winking face'], 0],
  ['😊', 'smiling face with smiling eyes', ['blush', 'eye', 'face', 'smile', 'smiling face with smiling eyes'], 0],
  ['😇', 'smiling face with halo', ['angel', 'face', 'fantasy', 'halo', 'innocent', 'smiling face with halo'], 0],
  ['🥰', 'smiling face with hearts', ['adore', 'crush', 'hearts', 'in love', 'smiling face with hearts'], 0],
  ['😍', 'smiling face with heart-eyes', ['eye', 'face', 'love', 'smile', 'smiling face with heart-eyes'], 0],
  ['🤩', 'star-struck', ['eyes', 'face', 'grinning', 'star', 'star-struck', 'starry-eyed'], 0],
  ['😘', 'face blowing a kiss', ['face', 'face blowing a kiss', 'kiss'], 0],
  ['😗', 'kissing face', ['face', 'kiss', 'kissing face'], 0],
  ['☺', 'smiling face', ['face', 'outlined', 'relaxed', 'smile', 'smiling face'], 0],
  ['😚', 'kissing face with closed eyes', ['closed', 'eye', 'face', 'kiss', 'kissing face with closed eyes'], 0],
  ['😙', 'kissing face with smiling eyes', ['eye', 'face', 'kiss', 'kissing face with smiling eyes', 'smile'], 0],
  ['🥲', 'smiling face with tear', ['grateful', 'proud', 'relieved', 'smiling', 'smiling face with tear', 'tear', 'touched'], 0],
  ['😋', 'face savoring food', ['delicious', 'face', 'face savoring food', 'savouring', 'smile', 'yum'], 0],
  ['😛', 'face with tongue', ['face', 'face with tongue', 'tongue'], 0],
  ['😜', 'winking face with tongue', ['eye', 'face', 'joke', 'tongue', 'wink', 'winking face with tongue'], 0],
  ['🤪', 'zany face', ['eye', 'goofy', 'large', 'small', 'zany face'], 0],
  ['😝', 'squinting face with tongue', ['eye', 'face', 'horrible', 'squinting face with tongue', 'taste', 'tongue'], 0],
  ['🤑', 'money-mouth face', ['face', 'money', 'money-mouth face', 'mouth'], 0],
  ['🤗', 'smiling face with open hands', ['face', 'hug', 'hugging', 'open hands', 'smiling face', 'smiling face with open hands'], 0],
  ['🤭', 'face with hand over mouth', ['face with hand over mouth', 'whoops', 'shock', 'sudden realization', 'surprise'], 0],
  ['🫢', '⊛ face with open eyes and hand over mouth', ['amazement', 'awe', 'disbelief', 'embarrass', 'scared', 'surprise'], 0],
  ['🫣', '⊛ face with peeking eye', ['captivated', 'peep', 'stare'], 0],
  ['🤫', 'shushing face', ['quiet', 'shush', 'shushing face'], 0],
  ['🤔', 'thinking face', ['face', 'thinking'], 0],
  ['🫡', '⊛ saluting face', ['ok', 'salute', 'sunny', 'troops', 'yes'], 0],
  ['🤐', 'zipper-mouth face', ['face', 'mouth', 'zipper', 'zipper-mouth face'], 0],
  ['🤨', 'face with raised eyebrow', ['distrust', 'face with raised eyebrow', 'skeptic', 'disapproval', 'disbelief', 'mild surprise', 'scepticism'], 0],
  ['😐', 'neutral face', ['deadpan', 'face', 'meh', 'neutral'], 0],
  ['😑', 'expressionless face', ['expressionless', 'face', 'inexpressive', 'meh', 'unexpressive'], 0],
  ['😶', 'face without mouth', ['face', 'face without mouth', 'mouth', 'quiet', 'silent'], 0],
  ['🫥', '⊛ dotted line face', ['depressed', 'disappear', 'hide', 'introvert', 'invisible'], 0],
  ['😶‍🌫️', 'face in clouds', ['absentminded', 'face in clouds', 'face in the fog', 'head in clouds'], 0],
  ['😏', 'smirking face', ['face', 'smirk', 'smirking face'], 0],
  ['😒', 'unamused face', ['face', 'unamused', 'unhappy'], 0],
  ['🙄', 'face with rolling eyes', ['eyeroll', 'eyes', 'face', 'face with rolling eyes', 'rolling'], 0],
  ['😬', 'grimacing face', ['face', 'grimace', 'grimacing face'], 0],
  ['😮‍💨', 'face exhaling', ['exhale', 'face exhaling', 'gasp', 'groan', 'relief', 'whisper', 'whistle'], 0],
  ['🤥', 'lying face', ['face', 'lie', 'lying face', 'pinocchio'], 0],
  ['😌', 'relieved face', ['face', 'relieved'], 0],
  ['😔', 'pensive face', ['dejected', 'face', 'pensive'], 0],
  ['😪', 'sleepy face', ['face', 'sleep', 'sleepy face'], 0],
  ['🤤', 'drooling face', ['drooling', 'face'], 0],
  ['😴', 'sleeping face', ['face', 'sleep', 'sleeping face', 'zzz'], 0],
  ['😷', 'face with medical mask', ['cold', 'doctor', 'face', 'face with medical mask', 'mask', 'sick'], 0],
  ['🤒', 'face with thermometer', ['face', 'face with thermometer', 'ill', 'sick', 'thermometer'], 0],
  ['🤕', 'face with head-bandage', ['bandage', 'face', 'face with head-bandage', 'hurt', 'injury'], 0],
  ['🤢', 'nauseated face', ['face', 'nauseated', 'vomit'], 0],
  ['🤮', 'face vomiting', ['face vomiting', 'puke', 'sick', 'vomit'], 0],
  ['🤧', 'sneezing face', ['face', 'gesundheit', 'sneeze', 'sneezing face'], 0],
  ['🥵', 'hot face', ['feverish', 'heat stroke', 'hot', 'hot face', 'red-faced', 'sweating'], 0],
  ['🥶', 'cold face', ['blue-faced', 'cold', 'cold face', 'freezing', 'frostbite', 'icicles'], 0],
  ['🥴', 'woozy face', ['dizzy', 'intoxicated', 'tipsy', 'uneven eyes', 'wavy mouth', 'woozy face'], 0],
  ['😵', 'face with crossed-out eyes', ['crossed-out eyes', 'dead', 'face', 'face with crossed-out eyes', 'knocked out'], 0],
  ['😵‍💫', 'face with spiral eyes', ['dizzy', 'face with spiral eyes', 'hypnotized', 'spiral', 'trouble', 'whoa'], 0],
  ['🤯', 'exploding head', ['exploding head', 'mind blown', 'shocked'], 0],
  ['🤠', 'cowboy hat face', ['cowboy', 'cowgirl', 'face', 'hat'], 0],
  ['🥳', 'partying face', ['celebration', 'hat', 'horn', 'party', 'partying face'], 0],
  ['🥸', 'disguised face', ['disguise', 'disguised face', 'face', 'glasses', 'incognito', 'nose'], 0],
  ['😎', 'smiling face with sunglasses', ['bright', 'cool', 'face', 'smiling face with sunglasses', 'sun', 'sunglasses'], 0],
  ['🤓', 'nerd face', ['face', 'geek', 'nerd'], 0],
  ['🧐', 'face with monocle', ['face with monocle', 'stuffy', 'wealthy'], 0],
  ['😕', 'confused face', ['confused', 'face', 'meh'], 0],
  ['🫤', '⊛ face with diagonal mouth', ['disappointed', 'meh', 'skeptical', 'unsure'], 0],
  ['😟', 'worried face', ['face', 'worried'], 0],
  ['🙁', 'slightly frowning face', ['face', 'frown', 'slightly frowning face'], 0],
  ['☹', 'frowning face', ['face', 'frown', 'frowning face'], 0],
  ['😮', 'face with open mouth', ['face', 'face with open mouth', 'mouth', 'open', 'sympathy'], 0],
  ['😯', 'hushed face', ['face', 'hushed', 'stunned', 'surprised'], 0],
  ['😲', 'astonished face', ['astonished', 'face', 'shocked', 'totally'], 0],
  ['😳', 'flushed face', ['dazed', 'face', 'flushed'], 0],
  ['🥺', 'pleading face', ['begging', 'mercy', 'pleading face', 'puppy eyes'], 0],
  ['🥹', '⊛ face holding back tears', ['angry', 'cry', 'proud', 'resist', 'sad'], 0],
  ['😦', 'frowning face with open mouth', ['face', 'frown', 'frowning face with open mouth', 'mouth', 'open'], 0],
  ['😧', 'anguished face', ['anguished', 'face'], 0],
  ['😨', 'fearful face', ['face', 'fear', 'fearful', 'scared'], 0],
  ['😰', 'anxious face with sweat', ['anxious face with sweat', 'blue', 'cold', 'face', 'rushed', 'sweat'], 0],
  ['😥', 'sad but relieved face', ['disappointed', 'face', 'relieved', 'sad but relieved face', 'whew'], 0],
  ['😢', 'crying face', ['cry', 'crying face', 'face', 'sad', 'tear'], 0],
  ['😭', 'loudly crying face', ['cry', 'face', 'loudly crying face', 'sad', 'sob', 'tear'], 0],
  ['😱', 'face screaming in fear', ['face', 'face screaming in fear', 'fear', 'munch', 'scared', 'scream'], 0],
  ['😖', 'confounded face', ['confounded', 'face'], 0],
  ['😣', 'persevering face', ['face', 'persevere', 'persevering face'], 0],
  ['😞', 'disappointed face', ['disappointed', 'face'], 0],
  ['😓', 'downcast face with sweat', ['cold', 'downcast face with sweat', 'face', 'sweat'], 0],
  ['😩', 'weary face', ['face', 'tired', 'weary'], 0],
  ['😫', 'tired face', ['face', 'tired'], 0],
  ['🥱', 'yawning face', ['bored', 'tired', 'yawn', 'yawning face'], 0],
  ['😤', 'face with steam from nose', ['face', 'face with steam from nose', 'triumph', 'won'], 0],
  ['😡', 'pouting face', ['angry', 'face', 'mad', 'pouting', 'rage', 'red'], 0],
  ['😠', 'angry face', ['anger', 'angry', 'face', 'mad'], 0],
  ['🤬', 'face with symbols on mouth', ['face with symbols on mouth', 'swearing', 'cursing'], 0],
  ['😈', 'smiling face with horns', ['face', 'fairy tale', 'fantasy', 'horns', 'smile', 'smiling face with horns'], 0],
  ['👿', 'angry face with horns', ['angry face with horns', 'demon', 'devil', 'face', 'fantasy', 'imp'], 0],
  ['💀', 'skull', ['death', 'face', 'fairy tale', 'monster', 'skull'], 0],
  ['☠', 'skull and crossbones', ['crossbones', 'death', 'face', 'monster', 'skull', 'skull and crossbones'], 0],
  ['💩', 'pile of poo', ['dung', 'face', 'monster', 'pile of poo', 'poo', 'poop'], 0],
  ['🤡', 'clown face', ['clown', 'face'], 0],
  ['👹', 'ogre', ['creature', 'face', 'fairy tale', 'fantasy', 'monster', 'ogre', 'troll'], 0],
  ['👺', 'goblin', ['creature', 'face', 'fairy tale', 'fantasy', 'goblin', 'monster'], 0],
  ['👻', 'ghost', ['creature', 'face', 'fairy tale', 'fantasy', 'ghost', 'monster'], 0],
  ['👽', 'alien', ['alien', 'creature', 'extraterrestrial', 'face', 'fantasy', 'ufo'], 0],
  ['👾', 'alien monster', ['alien', 'creature', 'extraterrestrial', 'face', 'monster', 'ufo'], 0],
  ['🤖', 'robot', ['face', 'monster', 'robot'], 0],
  ['😺', 'grinning cat', ['cat', 'face', 'grinning', 'mouth', 'open', 'smile'], 0],
  ['😸', 'grinning cat with smiling eyes', ['cat', 'eye', 'face', 'grin', 'grinning cat with smiling eyes', 'smile'], 0],
  ['😹', 'cat with tears of joy', ['cat', 'cat with tears of joy', 'face', 'joy', 'tear'], 0],
  ['😻', 'smiling cat with heart-eyes', ['cat', 'eye', 'face', 'heart', 'love', 'smile', 'smiling cat with heart-eyes'], 0],
  ['😼', 'cat with wry smile', ['cat', 'cat with wry smile', 'face', 'ironic', 'smile', 'wry'], 0],
  ['😽', 'kissing cat', ['cat', 'eye', 'face', 'kiss', 'kissing cat'], 0],
  ['🙀', 'weary cat', ['cat', 'face', 'oh', 'surprised', 'weary'], 0],
  ['😿', 'crying cat', ['cat', 'cry', 'crying cat', 'face', 'sad', 'tear'], 0],
  ['😾', 'pouting cat', ['cat', 'face', 'pouting'], 0],
  ['🙈', 'see-no-evil monkey', ['evil', 'face', 'forbidden', 'monkey', 'see', 'see-no-evil monkey'], 0],
  ['🙉', 'hear-no-evil monkey', ['evil', 'face', 'forbidden', 'hear', 'hear-no-evil monkey', 'monkey'], 0],
  ['🙊', 'speak-no-evil monkey', ['evil', 'face', 'forbidden', 'monkey', 'speak', 'speak-no-evil monkey'], 0],
  ['💋', 'kiss mark', ['kiss', 'kiss mark', 'lips'], 0],
  ['💌', 'love letter', ['heart', 'letter', 'love', 'mail'], 0],
  ['💘', 'heart with arrow', ['arrow', 'cupid', 'heart with arrow'], 0],
  ['💝', 'heart with ribbon', ['heart with ribbon', 'ribbon', 'valentine'], 0],
  ['💖', 'sparkling heart', ['excited', 'sparkle', 'sparkling heart'], 0],
  ['💗', 'growing heart', ['excited', 'growing', 'growing heart', 'nervous', 'pulse'], 0],
  ['💓', 'beating heart', ['beating', 'beating heart', 'heartbeat', 'pulsating'], 0],
  ['💞', 'revolving hearts', ['revolving', 'revolving hearts'], 0],
  ['💕', 'two hearts', ['love', 'two hearts'], 0],
  ['💟', 'heart decoration', ['heart', 'heart decoration'], 0],
  ['❣', 'heart exclamation', ['exclamation', 'heart exclamation', 'mark', 'punctuation'], 0],
  ['💔', 'broken heart', ['break', 'broken', 'broken heart'], 0],
  ['❤️‍🔥', 'heart on fire', ['burn', 'heart', 'heart on fire', 'love', 'lust', 'sacred heart'], 0],
  ['❤️‍🩹', 'mending heart', ['healthier', 'improving', 'mending', 'mending heart', 'recovering', 'recuperating', 'well'], 0],
  ['❤', 'red heart', ['heart', 'red heart'], 0],
  ['🧡', 'orange heart', ['orange', 'orange heart'], 0],
  ['💛', 'yellow heart', ['yellow', 'yellow heart'], 0],
  ['💚', 'green heart', ['green', 'green heart'], 0],
  ['💙', 'blue heart', ['blue', 'blue heart'], 0],
  ['💜', 'purple heart', ['purple', 'purple heart'], 0],
  ['🤎', 'brown heart', ['brown', 'heart'], 0],
  ['🖤', 'black heart', ['black', 'black heart', 'evil', 'wicked'], 0],
  ['🤍', 'white heart', ['heart', 'white'], 0],
  ['💯', 'hundred points', ['100', 'full', 'hundred', 'hundred points', 'score'], 0],
  ['💢', 'anger symbol', ['anger symbol', 'angry', 'comic', 'mad'], 0],
  ['💥', 'collision', ['boom', 'collision', 'comic'], 0],
  ['💫', 'dizzy', ['comic', 'dizzy', 'star'], 0],
  ['💦', 'sweat droplets', ['comic', 'splashing', 'sweat', 'sweat droplets'], 0],
  ['💨', 'dashing away', ['comic', 'dash', 'dashing away', 'running'], 0],
  ['🕳', 'hole', ['hole'], 0],
  ['💣', 'bomb', ['bomb', 'comic'], 0],
  ['💬', 'speech balloon', ['balloon', 'bubble', 'comic', 'dialog', 'speech'], 0],
  ['👁️‍🗨️', 'eye in speech bubble', ['eye', 'eye in speech bubble', 'speech bubble', 'witness'], 0],
  ['🗨', 'left speech bubble', ['dialog', 'left speech bubble', 'speech'], 0],
  ['🗯', 'right anger bubble', ['angry', 'balloon', 'bubble', 'mad', 'right anger bubble'], 0],
  ['💭', 'thought balloon', ['balloon', 'bubble', 'comic', 'thought'], 0],
  ['💤', 'zzz', ['comic', 'sleep', 'zzz'], 0],
  ['👋', 'waving hand', ['hand', 'wave', 'waving'], 1],
  ['🤚', 'raised back of hand', ['backhand', 'raised', 'raised back of hand'], 0],
  ['🖐', 'hand with fingers splayed', ['finger', 'hand', 'hand with fingers splayed', 'splayed'], 0],
  ['✋', 'raised hand', ['hand', 'high 5', 'high five', 'raised hand'], 0],
  ['🖖', 'vulcan salute', ['finger', 'hand', 'spock', 'vulcan', 'vulcan salute'], 0],
  ['🫱', '⊛ rightwards hand', ['hand', 'right', 'rightward'], 0],
  ['🫲', '⊛ leftwards hand', ['hand', 'left', 'leftward'], 0],
  ['🫳', '⊛ palm down hand', ['dismiss', 'drop', 'shoo'], 0],
  ['🫴', '⊛ palm up hand', ['beckon', 'catch', 'come', 'offer'], 0],
  ['👌', 'OK hand', ['hand', 'OK'], 0],
  ['🤌', 'pinched fingers', ['fingers', 'hand gesture', 'interrogation', 'pinched', 'sarcastic'], 0],
  ['🤏', 'pinching hand', ['pinching hand', 'small amount'], 0],
  ['✌', 'victory hand', ['hand', 'v', 'victory'], 0],
  ['🤞', 'crossed fingers', ['cross', 'crossed fingers', 'finger', 'hand', 'luck'], 0],
  ['🫰', '⊛ hand with index finger and thumb crossed', ['expensive', 'heart', 'love', 'money', 'snap'], 0],
  ['🤟', 'love-you gesture', ['hand', 'ILY', 'love-you gesture'], 0],
  ['🤘', 'sign of the horns', ['finger', 'hand', 'horns', 'rock-on', 'sign of the horns'], 0],
  ['🤙', 'call me hand', ['call', 'call me hand', 'hand'], 0],
  ['👈', 'backhand index pointing left', ['backhand', 'backhand index pointing left', 'finger', 'hand', 'index', 'point'], 0],
  ['👉', 'backhand index pointing right', ['backhand', 'backhand index pointing right', 'finger', 'hand', 'index', 'point'], 0],
  ['👆', 'backhand index pointing up', ['backhand', 'backhand index pointing up', 'finger', 'hand', 'point', 'up'], 0],
  ['🖕', 'middle finger', ['finger', 'hand', 'middle finger'], 0],
  ['👇', 'backhand index pointing down', ['backhand', 'backhand index pointing down', 'down', 'finger', 'hand', 'point'], 0],
  ['☝', 'index pointing up', ['finger', 'hand', 'index', 'index pointing up', 'point', 'up'], 0],
  ['🫵', '⊛ index pointing at the viewer', ['point', 'you'], 0],
  ['👍', 'thumbs up', ['+1', 'hand', 'thumb', 'thumbs up', 'up'], 0],
  ['👎', 'thumbs down', ['-1', 'down', 'hand', 'thumb', 'thumbs down'], 0],
  ['✊', 'raised fist', ['clenched', 'fist', 'hand', 'punch', 'raised fist'], 0],
  ['👊', 'oncoming fist', ['clenched', 'fist', 'hand', 'oncoming fist', 'punch'], 0],
  ['🤛', 'left-facing fist', ['fist', 'left-facing fist', 'leftwards'], 0],
  ['🤜', 'right-facing fist', ['fist', 'right-facing fist', 'rightwards'], 0],
  ['👏', 'clapping hands', ['clap', 'clapping hands', 'hand'], 0],
  ['🙌', 'raising hands', ['celebration', 'gesture', 'hand', 'hooray', 'raised', 'raising hands'], 0],
  ['🫶', '⊛ heart hands', ['love'], 0],
  ['👐', 'open hands', ['hand', 'open', 'open hands'], 0],
  ['🤲', 'palms up together', ['palms up together', 'prayer', 'cupped hands'], 0],
  ['🤝', 'handshake', ['agreement', 'hand', 'handshake', 'meeting', 'shake'], 0],
  ['🙏', 'folded hands', ['ask', 'folded hands', 'hand', 'high 5', 'high five', 'please', 'pray', 'thanks'], 0],
  ['✍', 'writing hand', ['hand', 'write', 'writing hand'], 0],
  ['💅', 'nail polish', ['care', 'cosmetics', 'manicure', 'nail', 'polish'], 0],
  ['🤳', 'selfie', ['camera', 'phone', 'selfie'], 0],
  ['💪', 'flexed biceps', ['biceps', 'comic', 'flex', 'flexed biceps', 'muscle'], 0],
  ['🦾', 'mechanical arm', ['accessibility', 'mechanical arm', 'prosthetic'], 0],
  ['🦿', 'mechanical leg', ['accessibility', 'mechanical leg', 'prosthetic'], 0],
  ['🦵', 'leg', ['kick', 'leg', 'limb'], 0],
  ['🦶', 'foot', ['foot', 'kick', 'stomp'], 0],
  ['👂', 'ear', ['body', 'ear'], 0],
  ['🦻', 'ear with hearing aid', ['accessibility', 'ear with hearing aid', 'hard of hearing'], 0],
  ['👃', 'nose', ['body', 'nose'], 0],
  ['🧠', 'brain', ['brain', 'intelligent'], 0],
  ['🫀', 'anatomical heart', ['anatomical', 'cardiology', 'heart', 'organ', 'pulse'], 0],
  ['🫁', 'lungs', ['breath', 'exhalation', 'inhalation', 'lungs', 'organ', 'respiration'], 0],
  ['🦷', 'tooth', ['dentist', 'tooth'], 0],
  ['🦴', 'bone', ['bone', 'skeleton'], 0],
  ['👀', 'eyes', ['eye', 'eyes', 'face'], 0],
  ['👁', 'eye', ['body', 'eye'], 0],
  ['👅', 'tongue', ['body', 'tongue'], 0],
  ['👄', 'mouth', ['lips', 'mouth'], 0],
  ['🫦', '⊛ biting lip', ['anxious', 'fear', 'flirting', 'nervous', 'uncomfortable', 'worried'], 0],
  ['👶', 'baby', ['baby', 'young'], 0],
  ['🧒', 'child', ['child', 'gender-neutral', 'unspecified gender', 'young'], 0],
  ['👦', 'boy', ['boy', 'young'], 0],
  ['👧', 'girl', ['girl', 'Virgo', 'young', 'zodiac'], 0],
  ['🧑', 'person', ['adult', 'gender-neutral', 'person', 'unspecified gender'], 0],
  ['👱', 'person: blond hair', ['blond', 'blond-haired person', 'hair', 'person: blond hair'], 0],
  ['👨', 'man', ['adult', 'man'], 0],
  ['🧔', 'person: beard', ['beard', 'person', 'person: beard', 'bewhiskered'], 0],
  ['🧔‍♂️', 'man: beard', ['beard', 'man', 'man: beard'], 0],
  ['🧔‍♀️', 'woman: beard', ['beard', 'woman', 'woman: beard'], 0],
  ['👨‍🦰', 'man: red hair', ['adult', 'man', 'red hair'], 0],
  ['👨‍🦱', 'man: curly hair', ['adult', 'curly hair', 'man'], 0],
  ['👨‍🦳', 'man: white hair', ['adult', 'man', 'white hair'], 0],
  ['👨‍🦲', 'man: bald', ['adult', 'bald', 'man'], 0],
  ['👩', 'woman', ['adult', 'woman'], 0],
  ['👩‍🦰', 'woman: red hair', ['adult', 'red hair', 'woman'], 0],
  ['🧑‍🦰', 'person: red hair', ['adult', 'gender-neutral', 'person', 'red hair', 'unspecified gender'], 0],
  ['👩‍🦱', 'woman: curly hair', ['adult', 'curly hair', 'woman'], 0],
  ['🧑‍🦱', 'person: curly hair', ['adult', 'curly hair', 'gender-neutral', 'person', 'unspecified gender'], 0],
  ['👩‍🦳', 'woman: white hair', ['adult', 'white hair', 'woman'], 0],
  ['🧑‍🦳', 'person: white hair', ['adult', 'gender-neutral', 'person', 'unspecified gender', 'white hair'], 0],
  ['👩‍🦲', 'woman: bald', ['adult', 'bald', 'woman'], 0],
  ['🧑‍🦲', 'person: bald', ['adult', 'bald', 'gender-neutral', 'person', 'unspecified gender'], 0],
  ['👱‍♀️', 'woman: blond hair', ['blond-haired woman', 'blonde', 'hair', 'woman', 'woman: blond hair'], 0],
  ['👱‍♂️', 'man: blond hair', ['blond', 'blond-haired man', 'hair', 'man', 'man: blond hair'], 0],
  ['🧓', 'older person', ['adult', 'gender-neutral', 'old', 'older person', 'unspecified gender'], 0],
  ['👴', 'old man', ['adult', 'man', 'old'], 0],
  ['👵', 'old woman', ['adult', 'old', 'woman'], 0],
  ['🙍', 'person frowning', ['frown', 'gesture', 'person frowning'], 0],
  ['🙍‍♂️', 'man frowning', ['frowning', 'gesture', 'man'], 0],
  ['🙍‍♀️', 'woman frowning', ['frowning', 'gesture', 'woman'], 0],
  ['🙎', 'person pouting', ['gesture', 'person pouting', 'pouting'], 0],
  ['🙎‍♂️', 'man pouting', ['gesture', 'man', 'pouting'], 0],
  ['🙎‍♀️', 'woman pouting', ['gesture', 'pouting', 'woman'], 0],
  ['🙅', 'person gesturing NO', ['forbidden', 'gesture', 'hand', 'person gesturing NO', 'prohibited'], 0],
  ['🙅‍♂️', 'man gesturing NO', ['forbidden', 'gesture', 'hand', 'man', 'man gesturing NO', 'prohibited'], 0],
  ['🙅‍♀️', 'woman gesturing NO', ['forbidden', 'gesture', 'hand', 'prohibited', 'woman', 'woman gesturing NO'], 0],
  ['🙆', 'person gesturing OK', ['gesture', 'hand', 'OK', 'person gesturing OK'], 0],
  ['🙆‍♂️', 'man gesturing OK', ['gesture', 'hand', 'man', 'man gesturing OK', 'OK'], 0],
  ['🙆‍♀️', 'woman gesturing OK', ['gesture', 'hand', 'OK', 'woman', 'woman gesturing OK'], 0],
  ['💁', 'person tipping hand', ['hand', 'help', 'information', 'person tipping hand', 'sassy', 'tipping'], 0],
  ['💁‍♂️', 'man tipping hand', ['man', 'man tipping hand', 'sassy', 'tipping hand'], 0],
  ['💁‍♀️', 'woman tipping hand', ['sassy', 'tipping hand', 'woman', 'woman tipping hand'], 0],
  ['🙋', 'person raising hand', ['gesture', 'hand', 'happy', 'person raising hand', 'raised'], 0],
  ['🙋‍♂️', 'man raising hand', ['gesture', 'man', 'man raising hand', 'raising hand'], 0],
  ['🙋‍♀️', 'woman raising hand', ['gesture', 'raising hand', 'woman', 'woman raising hand'], 0],
  ['🧏', 'deaf person', ['accessibility', 'deaf', 'deaf person', 'ear', 'hear'], 0],
  ['🧏‍♂️', 'deaf man', ['deaf', 'man'], 0],
  ['🧏‍♀️', 'deaf woman', ['deaf', 'woman'], 0],
  ['🙇', 'person bowing', ['apology', 'bow', 'gesture', 'person bowing', 'sorry'], 0],
  ['🙇‍♂️', 'man bowing', ['apology', 'bowing', 'favor', 'gesture', 'man', 'sorry'], 0],
  ['🙇‍♀️', 'woman bowing', ['apology', 'bowing', 'favor', 'gesture', 'sorry', 'woman'], 0],
  ['🤦', 'person facepalming', ['disbelief', 'exasperation', 'face', 'palm', 'person facepalming'], 0],
  ['🤦‍♂️', 'man facepalming', ['disbelief', 'exasperation', 'facepalm', 'man', 'man facepalming'], 0],
  ['🤦‍♀️', 'woman facepalming', ['disbelief', 'exasperation', 'facepalm', 'woman', 'woman facepalming'], 0],
  ['🤷', 'person shrugging', ['doubt', 'ignorance', 'indifference', 'person shrugging', 'shrug'], 0],
  ['🤷‍♂️', 'man shrugging', ['doubt', 'ignorance', 'indifference', 'man', 'man shrugging', 'shrug'], 0],
  ['🤷‍♀️', 'woman shrugging', ['doubt', 'ignorance', 'indifference', 'shrug', 'woman', 'woman shrugging'], 0],
  ['🧑‍⚕️', 'health worker', ['doctor', 'health worker', 'healthcare', 'nurse', 'therapist'], 0],
  ['👨‍⚕️', 'man health worker', ['doctor', 'healthcare', 'man', 'man health worker', 'nurse', 'therapist'], 0],
  ['👩‍⚕️', 'woman health worker', ['doctor', 'healthcare', 'nurse', 'therapist', 'woman', 'woman health worker'], 0],
  ['🧑‍🎓', 'student', ['graduate', 'student'], 0],
  ['👨‍🎓', 'man student', ['graduate', 'man', 'student'], 0],
  ['👩‍🎓', 'woman student', ['graduate', 'student', 'woman'], 0],
  ['🧑‍🏫', 'teacher', ['instructor', 'professor', 'teacher'], 0],
  ['👨‍🏫', 'man teacher', ['instructor', 'man', 'professor', 'teacher'], 0],
  ['👩‍🏫', 'woman teacher', ['instructor', 'professor', 'teacher', 'woman'], 0],
  ['🧑‍⚖️', 'judge', ['judge', 'justice', 'scales'], 0],
  ['👨‍⚖️', 'man judge', ['judge', 'justice', 'man', 'scales'], 0],
  ['👩‍⚖️', 'woman judge', ['judge', 'justice', 'scales', 'woman'], 0],
  ['🧑‍🌾', 'farmer', ['farmer', 'gardener', 'rancher'], 0],
  ['👨‍🌾', 'man farmer', ['farmer', 'gardener', 'man', 'rancher'], 0],
  ['👩‍🌾', 'woman farmer', ['farmer', 'gardener', 'rancher', 'woman'], 0],
  ['🧑‍🍳', 'cook', ['chef', 'cook'], 0],
  ['👨‍🍳', 'man cook', ['chef', 'cook', 'man'], 0],
  ['👩‍🍳', 'woman cook', ['chef', 'cook', 'woman'], 0],
  ['🧑‍🔧', 'mechanic', ['electrician', 'mechanic', 'plumber', 'tradesperson'], 0],
  ['👨‍🔧', 'man mechanic', ['electrician', 'man', 'mechanic', 'plumber', 'tradesperson'], 0],
  ['👩‍🔧', 'woman mechanic', ['electrician', 'mechanic', 'plumber', 'tradesperson', 'woman'], 0],
  ['🧑‍🏭', 'factory worker', ['assembly', 'factory', 'industrial', 'worker'], 0],
  ['👨‍🏭', 'man factory worker', ['assembly', 'factory', 'industrial', 'man', 'worker'], 0],
  ['👩‍🏭', 'woman factory worker', ['assembly', 'factory', 'industrial', 'woman', 'worker'], 0],
  ['🧑‍💼', 'office worker', ['architect', 'business', 'manager', 'office worker', 'white-collar'], 0],
  ['👨‍💼', 'man office worker', ['architect', 'business', 'man', 'man office worker', 'manager', 'white-collar'], 0],
  ['👩‍💼', 'woman office worker', ['architect', 'business', 'manager', 'white-collar', 'woman', 'woman office worker'], 0],
  ['🧑‍🔬', 'scientist', ['biologist', 'chemist', 'engineer', 'physicist', 'scientist'], 0],
  ['👨‍🔬', 'man scientist', ['biologist', 'chemist', 'engineer', 'man', 'physicist', 'scientist'], 0],
  ['👩‍🔬', 'woman scientist', ['biologist', 'chemist', 'engineer', 'physicist', 'scientist', 'woman'], 0],
  ['🧑‍💻', 'technologist', ['coder', 'developer', 'inventor', 'software', 'technologist'], 0],
  ['👨‍💻', 'man technologist', ['coder', 'developer', 'inventor', 'man', 'software', 'technologist'], 0],
  ['👩‍💻', 'woman technologist', ['coder', 'developer', 'inventor', 'software', 'technologist', 'woman'], 0],
  ['🧑‍🎤', 'singer', ['actor', 'entertainer', 'rock', 'singer', 'star'], 0],
  ['👨‍🎤', 'man singer', ['actor', 'entertainer', 'man', 'rock', 'singer', 'star'], 0],
  ['👩‍🎤', 'woman singer', ['actor', 'entertainer', 'rock', 'singer', 'star', 'woman'], 0],
  ['🧑‍🎨', 'artist', ['artist', 'palette'], 0],
  ['👨‍🎨', 'man artist', ['artist', 'man', 'palette'], 0],
  ['👩‍🎨', 'woman artist', ['artist', 'palette', 'woman'], 0],
  ['🧑‍✈️', 'pilot', ['pilot', 'plane'], 0],
  ['👨‍✈️', 'man pilot', ['man', 'pilot', 'plane'], 0],
  ['👩‍✈️', 'woman pilot', ['pilot', 'plane', 'woman'], 0],
  ['🧑‍🚀', 'astronaut', ['astronaut', 'rocket'], 0],
  ['👨‍🚀', 'man astronaut', ['astronaut', 'man', 'rocket'], 0],
  ['👩‍🚀', 'woman astronaut', ['astronaut', 'rocket', 'woman'], 0],
  ['🧑‍🚒', 'firefighter', ['firefighter', 'firetruck'], 0],
  ['👨‍🚒', 'man firefighter', ['firefighter', 'firetruck', 'man'], 0],
  ['👩‍🚒', 'woman firefighter', ['firefighter', 'firetruck', 'woman'], 0],
  ['👮', 'police officer', ['cop', 'officer', 'police'], 0],
  ['👮‍♂️', 'man police officer', ['cop', 'man', 'officer', 'police'], 0],
  ['👮‍♀️', 'woman police officer', ['cop', 'officer', 'police', 'woman'], 0],
  ['🕵', 'detective', ['detective', 'sleuth', 'spy'], 0],
  ['🕵️‍♂️', 'man detective', ['detective', 'man', 'sleuth', 'spy'], 0],
  ['🕵️‍♀️', 'woman detective', ['detective', 'sleuth', 'spy', 'woman'], 0],
  ['💂', 'guard', ['guard'], 0],
  ['💂‍♂️', 'man guard', ['guard', 'man'], 0],
  ['💂‍♀️', 'woman guard', ['guard', 'woman'], 0],
  ['🥷', 'ninja', ['fighter', 'hidden', 'ninja', 'stealth'], 0],
  ['👷', 'construction worker', ['construction', 'hat', 'worker'], 0],
  ['👷‍♂️', 'man construction worker', ['construction', 'man', 'worker'], 0],
  ['👷‍♀️', 'woman construction worker', ['construction', 'woman', 'worker'], 0],
  ['🫅', '⊛ person with crown', ['monarch', 'noble', 'regal', 'royalty'], 0],
  ['🤴', 'prince', ['prince'], 0],
  ['👸', 'princess', ['fairy tale', 'fantasy', 'princess'], 0],
  ['👳', 'person wearing turban', ['person wearing turban', 'turban'], 0],
  ['👳‍♂️', 'man wearing turban', ['man', 'man wearing turban', 'turban'], 0],
  ['👳‍♀️', 'woman wearing turban', ['turban', 'woman', 'woman wearing turban'], 0],
  ['👲', 'person with skullcap', ['cap', 'gua pi mao', 'hat', 'person', 'person with skullcap', 'skullcap'], 0],
  ['🧕', 'woman with headscarf', ['headscarf', 'hijab', 'mantilla', 'tichel', 'woman with headscarf', 'bandana', 'head kerchief'], 0],
  ['🤵', 'person in tuxedo', ['groom', 'person', 'person in tuxedo', 'tuxedo'], 0],
  ['🤵‍♂️', 'man in tuxedo', ['man', 'man in tuxedo', 'tuxedo'], 0],
  ['🤵‍♀️', 'woman in tuxedo', ['tuxedo', 'woman', 'woman in tuxedo'], 0],
  ['👰', 'person with veil', ['bride', 'person', 'person with veil', 'veil', 'wedding'], 0],
  ['👰‍♂️', 'man with veil', ['man', 'man with veil', 'veil'], 0],
  ['👰‍♀️', 'woman with veil', ['veil', 'woman', 'woman with veil'], 0],
  ['🤰', 'pregnant woman', ['pregnant', 'woman'], 0],
  ['🫃', '⊛ pregnant man', ['belly', 'bloated', 'full', 'pregnant'], 0],
  ['🫄', '⊛ pregnant person', ['belly', 'bloated', 'full', 'pregnant'], 0],
  ['🤱', 'breast-feeding', ['baby', 'breast', 'breast-feeding', 'nursing'], 0],
  ['👩‍🍼', 'woman feeding baby', ['baby', 'feeding', 'nursing', 'woman'], 0],
  ['👨‍🍼', 'man feeding baby', ['baby', 'feeding', 'man', 'nursing'], 0],
  ['🧑‍🍼', 'person feeding baby', ['baby', 'feeding', 'nursing', 'person'], 0],
  ['👼', 'baby angel', ['angel', 'baby', 'face', 'fairy tale', 'fantasy'], 0],
  ['🎅', 'Santa Claus', ['celebration', 'Christmas', 'claus', 'father', 'santa', 'Santa Claus'], 0],
  ['🤶', 'Mrs. Claus', ['celebration', 'Christmas', 'claus', 'mother', 'Mrs.', 'Mrs. Claus'], 0],
  ['🧑‍🎄', 'mx claus', ['Claus, christmas', 'mx claus'], 0],
  ['🦸', 'superhero', ['good', 'hero', 'heroine', 'superhero', 'superpower'], 0],
  ['🦸‍♂️', 'man superhero', ['good', 'hero', 'man', 'man superhero', 'superpower'], 0],
  ['🦸‍♀️', 'woman superhero', ['good', 'hero', 'heroine', 'superpower', 'woman', 'woman superhero'], 0],
  ['🦹', 'supervillain', ['criminal', 'evil', 'superpower', 'supervillain', 'villain'], 0],
  ['🦹‍♂️', 'man supervillain', ['criminal', 'evil', 'man', 'man supervillain', 'superpower', 'villain'], 0],
  ['🦹‍♀️', 'woman supervillain', ['criminal', 'evil', 'superpower', 'villain', 'woman', 'woman supervillain'], 0],
  ['🧙', 'mage', ['mage', 'sorcerer', 'sorceress', 'witch', 'wizard'], 0],
  ['🧙‍♂️', 'man mage', ['man mage', 'sorcerer', 'wizard'], 0],
  ['🧙‍♀️', 'woman mage', ['sorceress', 'witch', 'woman mage'], 0],
  ['🧚', 'fairy', ['fairy', 'Oberon', 'Puck', 'Titania'], 0],
  ['🧚‍♂️', 'man fairy', ['man fairy', 'Oberon', 'Puck'], 0],
  ['🧚‍♀️', 'woman fairy', ['Titania', 'woman fairy'], 0],
  ['🧛', 'vampire', ['Dracula', 'undead', 'vampire'], 0],
  ['🧛‍♂️', 'man vampire', ['Dracula', 'man vampire', 'undead'], 0],
  ['🧛‍♀️', 'woman vampire', ['undead', 'woman vampire'], 0],
  ['🧜', 'merperson', ['mermaid', 'merman', 'merperson', 'merwoman'], 0],
  ['🧜‍♂️', 'merman', ['merman', 'Triton'], 0],
  ['🧜‍♀️', 'mermaid', ['mermaid', 'merwoman'], 0],
  ['🧝', 'elf', ['elf', 'magical', 'LOTR style'], 0],
  ['🧝‍♂️', 'man elf', ['magical', 'man elf'], 0],
  ['🧝‍♀️', 'woman elf', ['magical', 'woman elf'], 0],
  ['🧞', 'genie', ['djinn', 'genie', '(non-human color)'], 0],
  ['🧞‍♂️', 'man genie', ['djinn', 'man genie'], 0],
  ['🧞‍♀️', 'woman genie', ['djinn', 'woman genie'], 0],
  ['🧟', 'zombie', ['undead', 'walking dead', 'zombie', '(non-human color)'], 0],
  ['🧟‍♂️', 'man zombie', ['man zombie', 'undead', 'walking dead'], 0],
  ['🧟‍♀️', 'woman zombie', ['undead', 'walking dead', 'woman zombie'], 0],
  ['🧌', '⊛ troll', ['fairy tale', 'fantasy', 'monster'], 0],
  ['💆', 'person getting massage', ['face', 'massage', 'person getting massage', 'salon'], 0],
  ['💆‍♂️', 'man getting massage', ['face', 'man', 'man getting massage', 'massage'], 0],
  ['💆‍♀️', 'woman getting massage', ['face', 'massage', 'woman', 'woman getting massage'], 0],
  ['💇', 'person getting haircut', ['barber', 'beauty', 'haircut', 'parlor', 'person getting haircut'], 0],
  ['💇‍♂️', 'man getting haircut', ['haircut', 'man', 'man getting haircut'], 0],
  ['💇‍♀️', 'woman getting haircut', ['haircut', 'woman', 'woman getting haircut'], 0],
  ['🚶', 'person walking', ['hike', 'person walking', 'walk', 'walking'], 0],
  ['🚶‍♂️', 'man walking', ['hike', 'man', 'man walking', 'walk'], 0],
  ['🚶‍♀️', 'woman walking', ['hike', 'walk', 'woman', 'woman walking'], 0],
  ['🧍', 'person standing', ['person standing', 'stand', 'standing'], 0],
  ['🧍‍♂️', 'man standing', ['man', 'standing'], 0],
  ['🧍‍♀️', 'woman standing', ['standing', 'woman'], 0],
  ['🧎', 'person kneeling', ['kneel', 'kneeling', 'person kneeling'], 0],
  ['🧎‍♂️', 'man kneeling', ['kneeling', 'man'], 0],
  ['🧎‍♀️', 'woman kneeling', ['kneeling', 'woman'], 0],
  ['🧑‍🦯', 'person with white cane', ['accessibility', 'blind', 'person with white cane'], 0],
  ['👨‍🦯', 'man with white cane', ['accessibility', 'blind', 'man', 'man with white cane'], 0],
  ['👩‍🦯', 'woman with white cane', ['accessibility', 'blind', 'woman', 'woman with white cane'], 0],
  ['🧑‍🦼', 'person in motorized wheelchair', ['accessibility', 'person in motorized wheelchair', 'wheelchair'], 0],
  ['👨‍🦼', 'man in motorized wheelchair', ['accessibility', 'man', 'man in motorized wheelchair', 'wheelchair'], 0],
  ['👩‍🦼', 'woman in motorized wheelchair', ['accessibility', 'wheelchair', 'woman', 'woman in motorized wheelchair'], 0],
  ['🧑‍🦽', 'person in manual wheelchair', ['accessibility', 'person in manual wheelchair', 'wheelchair'], 0],
  ['👨‍🦽', 'man in manual wheelchair', ['accessibility', 'man', 'man in manual wheelchair', 'wheelchair'], 0],
  ['👩‍🦽', 'woman in manual wheelchair', ['accessibility', 'wheelchair', 'woman', 'woman in manual wheelchair'], 0],
  ['🏃', 'person running', ['marathon', 'person running', 'running'], 0],
  ['🏃‍♂️', 'man running', ['man', 'marathon', 'racing', 'running'], 0],
  ['🏃‍♀️', 'woman running', ['marathon', 'racing', 'running', 'woman'], 0],
  ['💃', 'woman dancing', ['dance', 'dancing', 'woman'], 0],
  ['🕺', 'man dancing', ['dance', 'dancing', 'man'], 0],
  ['🕴', 'person in suit levitating', ['business', 'person', 'person in suit levitating', 'suit'], 0],
  ['👯', 'people with bunny ears', ['bunny ear', 'dancer', 'partying', 'people with bunny ears'], 0],
  ['👯‍♂️', 'men with bunny ears', ['bunny ear', 'dancer', 'men', 'men with bunny ears', 'partying'], 0],
  ['👯‍♀️', 'women with bunny ears', ['bunny ear', 'dancer', 'partying', 'women', 'women with bunny ears'], 0],
  ['🧖', 'person in steamy room', ['person in steamy room', 'sauna', 'steam room', 'hamam', 'steambath'], 0],
  ['🧖‍♂️', 'man in steamy room', ['man in steamy room', 'sauna', 'steam room'], 0],
  ['🧖‍♀️', 'woman in steamy room', ['sauna', 'steam room', 'woman in steamy room'], 0],
  ['🧗', 'person climbing', ['climber', 'person climbing'], 0],
  ['🧗‍♂️', 'man climbing', ['climber', 'man climbing'], 0],
  ['🧗‍♀️', 'woman climbing', ['climber', 'woman climbing'], 0],
  ['🤺', 'person fencing', ['fencer', 'fencing', 'person fencing', 'sword'], 0],
  ['🏇', 'horse racing', ['horse', 'jockey', 'racehorse', 'racing'], 0],
  ['⛷', 'skier', ['ski', 'skier', 'snow'], 0],
  ['🏂', 'snowboarder', ['ski', 'snow', 'snowboard', 'snowboarder'], 0],
  ['🏌', 'person golfing', ['ball', 'golf', 'person golfing'], 0],
  ['🏌️‍♂️', 'man golfing', ['golf', 'man', 'man golfing'], 0],
  ['🏌️‍♀️', 'woman golfing', ['golf', 'woman', 'woman golfing'], 0],
  ['🏄', 'person surfing', ['person surfing', 'surfing'], 0],
  ['🏄‍♂️', 'man surfing', ['man', 'surfing'], 0],
  ['🏄‍♀️', 'woman surfing', ['surfing', 'woman'], 0],
  ['🚣', 'person rowing boat', ['boat', 'person rowing boat', 'rowboat'], 0],
  ['🚣‍♂️', 'man rowing boat', ['boat', 'man', 'man rowing boat', 'rowboat'], 0],
  ['🚣‍♀️', 'woman rowing boat', ['boat', 'rowboat', 'woman', 'woman rowing boat'], 0],
  ['🏊', 'person swimming', ['person swimming', 'swim'], 0],
  ['🏊‍♂️', 'man swimming', ['man', 'man swimming', 'swim'], 0],
  ['🏊‍♀️', 'woman swimming', ['swim', 'woman', 'woman swimming'], 0],
  ['⛹', 'person bouncing ball', ['ball', 'person bouncing ball'], 0],
  ['⛹️‍♂️', 'man bouncing ball', ['ball', 'man', 'man bouncing ball'], 0],
  ['⛹️‍♀️', 'woman bouncing ball', ['ball', 'woman', 'woman bouncing ball'], 0],
  ['🏋', 'person lifting weights', ['lifter', 'person lifting weights', 'weight'], 0],
  ['🏋️‍♂️', 'man lifting weights', ['man', 'man lifting weights', 'weight lifter'], 0],
  ['🏋️‍♀️', 'woman lifting weights', ['weight lifter', 'woman', 'woman lifting weights'], 0],
  ['🚴', 'person biking', ['bicycle', 'biking', 'cyclist', 'person biking'], 0],
  ['🚴‍♂️', 'man biking', ['bicycle', 'biking', 'cyclist', 'man'], 0],
  ['🚴‍♀️', 'woman biking', ['bicycle', 'biking', 'cyclist', 'woman'], 0],
  ['🚵', 'person mountain biking', ['bicycle', 'bicyclist', 'bike', 'cyclist', 'mountain', 'person mountain biking'], 0],
  ['🚵‍♂️', 'man mountain biking', ['bicycle', 'bike', 'cyclist', 'man', 'man mountain biking', 'mountain'], 0],
  ['🚵‍♀️', 'woman mountain biking', ['bicycle', 'bike', 'biking', 'cyclist', 'mountain', 'woman'], 0],
  ['🤸', 'person cartwheeling', ['cartwheel', 'gymnastics', 'person cartwheeling'], 0],
  ['🤸‍♂️', 'man cartwheeling', ['cartwheel', 'gymnastics', 'man', 'man cartwheeling'], 0],
  ['🤸‍♀️', 'woman cartwheeling', ['cartwheel', 'gymnastics', 'woman', 'woman cartwheeling'], 0],
  ['🤼', 'people wrestling', ['people wrestling', 'wrestle', 'wrestler'], 0],
  ['🤼‍♂️', 'men wrestling', ['men', 'men wrestling', 'wrestle'], 0],
  ['🤼‍♀️', 'women wrestling', ['women', 'women wrestling', 'wrestle'], 0],
  ['🤽', 'person playing water polo', ['person playing water polo', 'polo', 'water'], 0],
  ['🤽‍♂️', 'man playing water polo', ['man', 'man playing water polo', 'water polo'], 0],
  ['🤽‍♀️', 'woman playing water polo', ['water polo', 'woman', 'woman playing water polo'], 0],
  ['🤾', 'person playing handball', ['ball', 'handball', 'person playing handball'], 0],
  ['🤾‍♂️', 'man playing handball', ['handball', 'man', 'man playing handball'], 0],
  ['🤾‍♀️', 'woman playing handball', ['handball', 'woman', 'woman playing handball'], 0],
  ['🤹', 'person juggling', ['balance', 'juggle', 'multitask', 'person juggling', 'skill'], 0],
  ['🤹‍♂️', 'man juggling', ['juggling', 'man', 'multitask'], 0],
  ['🤹‍♀️', 'woman juggling', ['juggling', 'multitask', 'woman'], 0],
  ['🧘', 'person in lotus position', ['meditation', 'person in lotus position', 'yoga', 'serenity'], 0],
  ['🧘‍♂️', 'man in lotus position', ['man in lotus position', 'meditation', 'yoga'], 0],
  ['🧘‍♀️', 'woman in lotus position', ['meditation', 'woman in lotus position', 'yoga'], 0],
  ['🛀', 'person taking bath', ['bath', 'bathtub', 'person taking bath'], 0],
  ['🛌', 'person in bed', ['hotel', 'person in bed', 'sleep'], 0],
  ['🧑‍🤝‍🧑', 'people holding hands', ['couple', 'hand', 'hold', 'holding hands', 'people holding hands', 'person'], 0],
  ['👭', 'women holding hands', ['couple', 'hand', 'holding hands', 'women', 'women holding hands'], 0],
  ['👫', 'woman and man holding hands', ['couple', 'hand', 'hold', 'holding hands', 'man', 'woman', 'woman and man holding hands'], 0],
  ['👬', 'men holding hands', ['couple', 'Gemini', 'holding hands', 'man', 'men', 'men holding hands', 'twins', 'zodiac'], 0],
  ['💏', 'kiss', ['couple', 'kiss'], 0],
  ['👩‍❤️‍💋‍👨', 'kiss: woman, man', ['couple', 'kiss', 'man', 'woman'], 0],
  ['👨‍❤️‍💋‍👨', 'kiss: man, man', ['couple', 'kiss', 'man'], 0],
  ['👩‍❤️‍💋‍👩', 'kiss: woman, woman', ['couple', 'kiss', 'woman'], 0],
  ['💑', 'couple with heart', ['couple', 'couple with heart', 'love'], 0],
  ['👩‍❤️‍👨', 'couple with heart: woman, man', ['couple', 'couple with heart', 'love', 'man', 'woman'], 0],
  ['👨‍❤️‍👨', 'couple with heart: man, man', ['couple', 'couple with heart', 'love', 'man'], 0],
  ['👩‍❤️‍👩', 'couple with heart: woman, woman', ['couple', 'couple with heart', 'love', 'woman'], 0],
  ['👪', 'family', ['family'], 0],
  ['👨‍👩‍👦', 'family: man, woman, boy', ['boy', 'family', 'man', 'woman'], 0],
  ['👨‍👩‍👧', 'family: man, woman, girl', ['family', 'girl', 'man', 'woman'], 0],
  ['👨‍👩‍👧‍👦', 'family: man, woman, girl, boy', ['boy', 'family', 'girl', 'man', 'woman'], 0],
  ['👨‍👩‍👦‍👦', 'family: man, woman, boy, boy', ['boy', 'family', 'man', 'woman'], 0],
  ['👨‍👩‍👧‍👧', 'family: man, woman, girl, girl', ['family', 'girl', 'man', 'woman'], 0],
  ['👨‍👨‍👦', 'family: man, man, boy', ['boy', 'family', 'man'], 0],
  ['👨‍👨‍👧', 'family: man, man, girl', ['family', 'girl', 'man'], 0],
  ['👨‍👨‍👧‍👦', 'family: man, man, girl, boy', ['boy', 'family', 'girl', 'man'], 0],
  ['👨‍👨‍👦‍👦', 'family: man, man, boy, boy', ['boy', 'family', 'man'], 0],
  ['👨‍👨‍👧‍👧', 'family: man, man, girl, girl', ['family', 'girl', 'man'], 0],
  ['👩‍👩‍👦', 'family: woman, woman, boy', ['boy', 'family', 'woman'], 0],
  ['👩‍👩‍👧', 'family: woman, woman, girl', ['family', 'girl', 'woman'], 0],
  ['👩‍👩‍👧‍👦', 'family: woman, woman, girl, boy', ['boy', 'family', 'girl', 'woman'], 0],
  ['👩‍👩‍👦‍👦', 'family: woman, woman, boy, boy', ['boy', 'family', 'woman'], 0],
  ['👩‍👩‍👧‍👧', 'family: woman, woman, girl, girl', ['family', 'girl', 'woman'], 0],
  ['👨‍👦', 'family: man, boy', ['boy', 'family', 'man'], 0],
  ['👨‍👦‍👦', 'family: man, boy, boy', ['boy', 'family', 'man'], 0],
  ['👨‍👧', 'family: man, girl', ['family', 'girl', 'man'], 0],
  ['👨‍👧‍👦', 'family: man, girl, boy', ['boy', 'family', 'girl', 'man'], 0],
  ['👨‍👧‍👧', 'family: man, girl, girl', ['family', 'girl', 'man'], 0],
  ['👩‍👦', 'family: woman, boy', ['boy', 'family', 'woman'], 0],
  ['👩‍👦‍👦', 'family: woman, boy, boy', ['boy', 'family', 'woman'], 0],
  ['👩‍👧', 'family: woman, girl', ['family', 'girl', 'woman'], 0],
  ['👩‍👧‍👦', 'family: woman, girl, boy', ['boy', 'family', 'girl', 'woman'], 0],
  ['👩‍👧‍👧', 'family: woman, girl, girl', ['family', 'girl', 'woman'], 0],
  ['🗣', 'speaking head', ['face', 'head', 'silhouette', 'speak', 'speaking'], 0],
  ['👤', 'bust in silhouette', ['bust', 'bust in silhouette', 'silhouette'], 0],
  ['👥', 'busts in silhouette', ['bust', 'busts in silhouette', 'silhouette'], 0],
  ['🫂', 'people hugging', ['goodbye', 'hello', 'hug', 'people hugging', 'thanks'], 0],
  ['👣', 'footprints', ['clothing', 'footprint', 'footprints', 'print'], 0],
];